### ISSUE TITLE
Scaling wrong on validator graph

### ISSUE THREAD

**Issue by handelaar2** [gobitfly/eth2-beaconchain-explorer#1]
he Y-axis shows incorrect scaling (all ticks are the same)
<img width="1065" alt="Screenshot 2019-11-23 at 11 20 40" src="https://user-images.githubusercontent.com/28559038/69477175-4e436b80-0de3-11ea-8176-cb447827c5b5.png">

**Comment by handelaar2** [comment]
Just read the project will be switching to different graph library. Let's wait for that

**Comment by ppratscher** [comment]
We just show 2 decimal digits on the y axis. If the validator did join recently the balance won’t have changed enough to warrant a scale change. Can be fixed by showing 3 digits instead of 2.
