### ISSUE TITLE
Node stats link is going to "Eth2 Testnet Statistics"

### ISSUE THREAD

**Issue by calumtomeny** [gobitfly/eth2-beaconchain-explorer#1004]
**Reproduction steps**
Click on "Nodes" under the "Stats" menu item.

![image](https://user-images.githubusercontent.com/939917/130617417-544dcfff-4d2f-4bcf-bed2-b457da5b535e.png)

**Actual Result**
The website https://eth2.ethernodes.org/ loads.

**Expected Result** 
Either a page loads with the stats for the nodes of the Live network or the button doesn't exist at all

**Comment by Buttaa** [comment]
Eth2 ethernodes was removed from beaconcha.in for now.
