### ISSUE TITLE
emails not going out

### ISSUE THREAD

**Issue by owocki** [gobitfly/eth2-beaconchain-explorer#1013]
didnt get my sign up email so went to https://beaconcha.in/resend to get it resent. pressed submit and got this

https://bits.owocki.com/mXuKr1dw

**Comment by guybrush** [comment]
We are sending at most `N` emails per day to the same email-address. Maybe you tried to authenticate with the same email multiple times until you ran in our ratelimit?

**Comment by owocki** [comment]
i tried to login once, and reset my password once
