### ISSUE TITLE
API is failing

### ISSUE THREAD

**Issue by vpbxpdh** [gobitfly/eth2-beaconchain-explorer#1021]
When we access the following  -->> https://beaconcha.in/api/v1/validator/28261,28262,46896/performance

we get a response of -->>>> PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 129725 [running]:

**Comment by Buttaa** [comment]
> When we access the following -->> https://beaconcha.in/api/v1/validator/28261,28262,46896/performance
> 
> we get a response of -->>>> PANIC: runtime error: invalid memory address or nil pointer dereference goroutine 129725 [running]:

Hi, the issues seems to be solved. Closing issue, please open if it persists on your end.
