### ISSUE TITLE
Pending validator page showing wrong data

### ISSUE THREAD

**Issue by Jay-Way** [gobitfly/eth2-beaconchain-explorer#1036]
The information shown on the page https://beaconcha.in/validators#pending is not correct, all of the shown validators are already activated. The number displayed on top (In the dropdown where you toggle between active/pending/slashed) seems to be correct, but the data displayed in the table isn't.

I would expect the same data as here, on a different explorer: https://beaconscan.com/validators#pending

**Comment by Buttaa** [comment]
@Jay-Way This was fixed recently -- please re-open this issue if the issue still persists on your end.

**Comment by Jay-Way** [comment]
Yep it seems to be correct now. Danke Buttaa! :relaxed:
