### ISSUE TITLE
Allow Large Users to Purchase Premium Services and Additional Validators on the Dashboard for a Per-Validator Monthly Fee

### ISSUE THREAD

**Issue by GDGitReporter** [gobitfly/eth2-beaconchain-explorer#1064]
The beaconcha.in dashboard is hard-capped at 100 validators, with no option to increase that.

The mobile app allows users to subscribe for $24.49 per month to add up to 280 validators on their mobile dashboard.

The web dashboard should offer a similar feature. But there is no particular reason it needs to be capped at 280 validators.

Suggestion: Allow users to subscribe for $0.10 per month per validator to have access to the premium services, including more than 100 validators on both the mobile and web versions.

If a user has 150 validators, they would pay $15 per month, and could have 150 validators on their web and mobile app.

If a user has 800 validators, they would pay $80 per month.

If a user has just 10 validators, they could pay $1 per month to get access to the other premium features, even though they aren't hitting the 100 validator cap.

Right now the premium subscription only appeals to a very small subset of stakers -- those with between about 125-280 validators.

Less than 100 validators -- free version is fine
100-125 validators -- free version works for the first 100, and the rest are okay without; it's not worth paying $25/month for the incremental data
125-280 validators -- target customers!
281 and up -- These whales can't access all their validators on the dashboard anyway, so why subscribe?

You might also find that by adding a per-validator subscription, users with just 1 or 2 validators might subscribe just to get access to additional features like custom alerts and no ads. You could have a minimum charge of $1 per month, or $10 per year to keep the accounting easier. Or license the validators in blocks of 10 for $1 per month.

**Comment by GDGitReporter** [comment]
See also: 

https://github.com/gobitfly/eth2-beaconchain-explorer-app/issues/29

**Comment by manuelsc** [comment]
Hi @GDGitReporter thanks for the suggestion.

You can increase the dashboard limit on beaconcha.in as well by upgrading to premium: https://beaconcha.in/premium
This premium subscription is shared with mobile and web, so any purchase from the app gets you premium features on web too and vice versa.

We are working on providing support for more than 280 validators for the whale package in the near to medium future.

**Comment by he1-sim** [comment]
👍 Und los

**Comment by Grey007** [comment]
Hey team,

Any update on this? It's a great product and would like to use it for >500 validators. Is there anyway to "allow" more validators on an account?

**Comment by Buttaa** [comment]
@0x4Graham this will be a feature in our dashboard which is planned for Q4 this year!
