### ISSUE TITLE
Show light client sync committee duties

### ISSUE THREAD

**Issue by torfbolt** [gobitfly/eth2-beaconchain-explorer#1110]
As a staker, I would like to see if one of my validators is currently or in the upcoming period (256 epochs) part of the light client sync committee introduced with Altair. Since there are large rewards for fulfilling and large penalties for missing this duty, it is essential to avoid doing planned maintenance on a node while one of its validators is part of the sync committee. Having this information displayed on beaconcha.in would be very helpful. I would envision it something like this:

* In the validator overview, have a prominent notification of "Active Sync Committee Duty" or "Upcoming Sync Committee Duty", respectively.
* Similarly in the Dashboard and App, show these notifications if one of the validators is part of the committee.
* Nice to have: mails and/or push messages as soon as a validator is elected for sync committe duty in the upcoming period. Possibly another message when it is going from upcoming to active duty.
* Also nice to have: an overview page to see the set of all 512 current committee members.

**Comment by iiqqrs** [comment]
I agree this is highly desired.

**Comment by Othello16** [comment]
Agreed, took me by suprise, glad I didn't just update this morning like I had planned. I thought either the price of ETH skyrocted, i was high, or Eth broke and so was I. This would be really helpful.

**Comment by DigiDr** [comment]
Came to this thread after making the mistake of taking a node offline during sync committee duties - but i had no way of knowing. Is this being worked on?

**Comment by Buttaa** [comment]
Hi @torfbolt ,
Most of your suggestions were added. The overview page is missing but it's in our backlog.
