### ISSUE TITLE
Initial 32 ETH deposit appears in income history

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#1112]
https://beaconcha.in/user/rewards?validators=500%2C250000&currency=eur&days=1609455600-1635721199

**Comment by chrishobcroft** [comment]
This is the only issue in an otherwise excellent service...

**Comment by Buttaa** [comment]
https://github.com/gobitfly/eth2-beaconchain-explorer/issues/1258
