### ISSUE TITLE
Make graffitiwall less verbose, allow prefix

### ISSUE THREAD

**Issue by 0xKiwi** [gobitfly/eth2-beaconchain-explorer#112]
Hello beaconcha.in! Love the work you guys are doing! Keep it up :smile: 

Experimentation with the graffiti field of a block is absolutely creative, love the ideas! Although, one issue it brings up is that we are unable to tell which validators belong to who from purely the graffiti. This may cause some issues with detecting forks, and restricts implementation teams to only using purely identifiable graffiti, so any looker can tell which block is from who.

Now, while adding a prefix would be great, an issue with this the graffiti field in a block only allows for 32 bytes, 28 of which are currently being taken up by `graffitiwall:280:315:#6060ff`, leaving only 4 bytes for a prefix. But along with support for a prefix, I propose making the graffitiwall test less verbose. Possible alternatives could be:
* `wall:280:315:#6060ff` (20 bytes)
* `:280:315:#6060ff`(15 bytes)
* `gw:280:315:#6060ff` (18 bytes)

With the prefix, this could be like: `prylabs:280:315:#6060ff` (20 bytes). The prefix could also be used for any future "on-hover" features planned.

One other option is to also use #RGB instead of #RRGGBB, but this would limit the color spectrum of the wall at little gain.

Anyways, I know this isn't a priority, and not something of importance currently. But I'm looking into how we can make graffiti more fun for our users in Prysm and an issue with the graffitiwall is the inability to tell whose block is who. 

Thank you!

**Comment by peterbitfly** [comment]
closed with https://github.com/gobitfly/eth2-beaconchain-explorer/pull/1167
