### ISSUE TITLE
2 blocks of the same slot show "proposed"

### ISSUE THREAD

**Issue by stefa2k** [gobitfly/eth2-beaconchain-explorer#113]
As shown here:
https://www.beaconcha.in/validator/38052
https://www.beaconcha.in/validator/38124

**Comment by ppratscher** [comment]
This has been fixed in https://github.com/gobitfly/eth2-beaconchain-explorer/commit/b33cbd49a7d4826e9de49785b79e329d53872c18

Will require a full resync of the explorer to take effect.
