### ISSUE TITLE
Relax "attestation missed" notification to only notify after several missing attesations

### ISSUE THREAD

**Issue by dankrad** [gobitfly/eth2-beaconchain-explorer#1158]
As an at home staker, it is normal to miss some attestations -- e.g. the broadband probably reconnects once per day, leading to some minutes of downtime. This means it is very common to get missing attestation notification.

Much more rarely, a validator actually goes down and you need to intervene. Unfortunately, it is easy to miss this because one tends to ignore notifications that come in very regularly. It would be nice to have a setting where you don't get notified when a single attestation is missing but only on extended downtime of a validator -- e.g. after a number of attestations are missing, like 5-10, but ideally adjustable.

**Comment by guybrush** [comment]
I think this is a good idea, it will take some time to implement though.

Thank you for the suggestion we will definitely put it on our list!

**Comment by Buttaa** [comment]
@dankrad , @superphiz the new notification type is [now available](https://twitter.com/beaconcha_in/status/1580098977172627457)!
