### ISSUE TITLE
unknown method ListBlocksAltair for service ethereum.eth.v1alpha1.BeaconChain

### ISSUE THREAD

**Issue by zhenli-developer** [gobitfly/eth2-beaconchain-explorer#1165]
ListBlocksAltair did not find method ListBlocksAltair in Prysm

**Comment by zhenli-developer** [comment]
> 

ERRO[0000] error retrieving last blocks from backend node: rpc error: code = Unimplemented desc = unknown method ListBlocksAltair for service ethereum.eth.v1alpha1.BeaconChain  module=exporter

**Comment by guybrush** [comment]
Sorry right now the exporter only works with lighthouse. We will support prysm (and other clients) again but it will take some time (merge is coming and we want to focus on most important things first).

**Comment by hewison-chris** [comment]
Why is this closed as completed?

**Comment by ManuelMaM** [comment]
I'm still getting this error, is geth not implemented yet??? On the README says to use geth....
