### ISSUE TITLE
Issues with pagination

### ISSUE THREAD

**Issue by PandaWhisperer** [gobitfly/eth2-beaconchain-explorer#117]
## Summary
I found a few issues with the pagination function for search results. 
1. The wrong total is shown (total number of validators instead of number of search results)
2. The last page shows the wrong view count (next decimal)
3. The "Last" result button jumps to nowhere.

## Details

A picture says more than a thousand words:

<img width="1398" alt="Screen Shot 2020-06-11 at 11 25 04 PM" src="https://user-images.githubusercontent.com/749244/84471393-7c36b300-ac42-11ea-9ff8-5429c8aa411e.png">

I noticed this when using the search function to find validators by deposit address. I was expecting the pagination to show the total number of results found, but instead if seems to be showing the number of ALL known validators.

Additionally, left of the red circle it also shows the wrong count: "61 to 70", when in fact there are 63 results (so it should read "61 to 63").

Finally, when clicking the "Last" button I was expecting to end up on this same page (i.e. page 6). Instead, it shows an empty list (possibly page 1,731). The only way to get the last result page is to repeatedly click "Next".

Note that when I am already on the last page, the "Next" and "Last" buttons are not disabled. Clicking on either on them leads to an empty table.

**Comment by guybrush** [comment]
This is fixed in da269b1495557512b60f9286d6bc07f96cc14cf3

Please let me know if that is not the case :)

**Comment by PandaWhisperer** [comment]
@guybrush it's working as expected now, thank you! 🎉 😄
