### ISSUE TITLE
average daily validator income

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#1197]
The beaconcha.in [knowledge base](https://kb.beaconcha.in/beaconcha.in-explorer/eth2-charts) has a section titled "Average daily validator income" which links to https://beaconcha.in/charts/validator_income. It looks like that link is not working. Where can I find a graph of daily validator income? :)

<img width="890" alt="Screenshot 2022-01-17 at 14 56 24" src="https://user-images.githubusercontent.com/731743/149792157-b05e0f2a-4638-486f-9619-dd8f99989365.png">

**Comment by Buttaa** [comment]
> The beaconcha.in [knowledge base](https://kb.beaconcha.in/beaconcha.in-explorer/eth2-charts) has a section titled "Average daily validator income" which links to https://beaconcha.in/charts/validator_income. It looks like that link is not working. Where can I find a graph of daily validator income? :)
> 
> <img alt="Screenshot 2022-01-17 at 14 56 24" width="890" src="https://user-images.githubusercontent.com/731743/149792157-b05e0f2a-4638-486f-9619-dd8f99989365.png">

Pretty sure we disabled it because of performance reasons. 
Maybe @guybrush can say whether our recent performance improvements are sufficient or not :D

**Comment by Buttaa** [comment]
@JustinDrake the chart was removed a long time ago due to DB issues. Instead, a more reliable metric has been added https://beaconcha.in/ethstore
