### ISSUE TITLE
search by state root

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#1200]
I find myself wanting to search beaconcha.in by state root, similar to searching by block root (which is already supported). For example searching for `0x71ddf39322af21eeabda04f605992ab5027533eb8e9ab915075d432a886c6e51` would bring the user to https://beaconcha.in/block/bacd20f09da907734434f052bd4c9503aa16bab1960e89ea20610d08d064481c

**Comment by Buttaa** [comment]
@JustinDrake this should work now, thanks :)

https://beaconcha.in/block/0x71ddf39322af21eeabda04f605992ab5027533eb8e9ab915075d432a886c6e51
