### ISSUE TITLE
Public Keys vs Addresses in ETH2

### ISSUE THREAD

**Issue by simibac** [gobitfly/eth2-beaconchain-explorer#1204]
1. Why do we reference ETH2 validators by their public key while in ETH1 we use addresses for that?
2. After the merge, can we expect that we also use addresses for validators?
2. Why are public keys in ETH1 128 chars long (e.g. `21d5fd65a7597237050a94e3669d38d8a060d87627a956db18a1693fd9fe1bc0a39fb4b0eac47ebd6c50f83d9c4a04e8d039c88bc4db6a547d1b7e111d0853b1` taken from https://asecuritysite.com/encryption/ethadd) while ETH2 are only 96 (`0x833bf8a530768ca6b6afa664ab11adefd5d445be13e7e27a4889850dd8484e0ed957a0d2a86f7625b64936fabe2572fc` taken from beaconcha.in) chars long?

**Comment by Buttaa** [comment]
hi, i would suggest asking those questions in the r&d discord server 😅
