### ISSUE TITLE
Change go.mod module name, so that it can be imported from other projects

### ISSUE THREAD

**Issue by alrevuelta** [gobitfly/eth2-beaconchain-explorer#1211]
Just wondering if it would be possible to change the [go.mod](https://github.com/gobitfly/eth2-beaconchain-explorer/blob/master/go.mod#L1) module name from `eth2-exporter` to `github.com/gobitfly/eth2-beaconchain-explorer` or any other name with the GitHub prefix. This will allow other go projects to easily import your packages and use them. To the best of my knowledge, this is a common practice in golang repos.

**Comment by recy21** [comment]
Thank you for your interest in our project.
Created an internal ticket, will update here if we have new information. (currently a lot of work, will take a while)

**Comment by guybrush** [comment]
fixed in #2915
