### ISSUE TITLE
Edit validator details no longer supports MyEtherWallet (MEW) signature

### ISSUE THREAD

**Issue by barnabasbusa** [gobitfly/eth2-beaconchain-explorer#1220]
MyEtherWallet signature type has been changed to version 3. 
New signature JSON format look the following:
```json
{
  "address": "0xba123...eb2e29",
  "msg": "0x626561636f6e6368612e696e",
  "sig": "2d3d558......7421c",
  "version": "3",
  "signer": "MEW"
}
```
When try to use this signature type on beaconcha.in the following error message shows:
```
the provided signature is invalid
```

In comparison with mycrypto signore where the JSON format is the following: 
```json
{
  "address": "0xba123...eb2e29",
  "msg": "beaconcha.in",
  "sig": "0x2d3d558a5....fe8787421c",
  "version": "2"
}
```
Even though the actual signature seems to be exactly the same, the msg value seems to be a hexadecimal representation of "beaconcha.in" string. 

0x626561636f6e6368612e696e == "beaconcha.in" 

I propose a fix where the signature value should be accepted whether its a string or hexadecimal representation.

**Comment by Buttaa** [comment]
@barnabasbusa this was fixed a while ago, please re-open if it does not work!
