### ISSUE TITLE
Eth2deposits: No beacon chain deposits found for this validator

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#123]
Displays this for already active validators from the genesis event.

![firefox_2020-06-14_10-41-15](https://user-images.githubusercontent.com/26490734/84588922-941d5b00-ae2b-11ea-8a49-0d73c5331697.png)

**Comment by guybrush** [comment]
Right now it looks like it is working? https://beaconcha.in/validator/2872#deposits

Not sure though how exactly this looks during waiting for the chain-start. We depend on the beacon-node-api to geht ETH2-deposits, so once it returns the deposits they should be displayed.

**Comment by guybrush** [comment]
I think this is fixed by 416eb3d637970c1fd17d94e7ca692d5915b0cd23
