### ISSUE TITLE
Add "Sync Committee" column to dashboard

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#1237]
An additional sortable column on the dashboard for Sync Committee for each validator -  "Y" or "N"

![Discord_NDRVVdJ2QG](https://user-images.githubusercontent.com/26490734/153702545-c69bf291-1b0b-49c9-ac5a-0d27b1a3bc67.png)

https://beaconcha.in/dashboard?validators=1

**Comment by suriyawutkhongprom** [comment]
> An additional sortable column on the dashboard for Sync Committee for each validator -  "Y" or "N"
> 
> ![Discord_NDRVVdJ2QG](https://user-images.githubusercontent.com/26490734/153702545-c69bf291-1b0b-49c9-ac5a-0d27b1a3bc67.png)
> 
> https://beaconcha.in/dashboard
