### ISSUE TITLE
Header: "Epoch Slot" to "Epoch current_slot/scheduled_slot" 

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#124]
Currently shows the last scheduled slot until a new epoch starts. 
Better UX by showing `Epoch, current_slot / last_scheduled_slot`. 

![firefox_2020-06-14_12-09-42](https://user-images.githubusercontent.com/26490734/84590569-1dd32580-ae38-11ea-903f-1fef5386da55.png)

**Comment by qu0b** [comment]
Also add a finalization-gap indicator to the status field if the gap is high.
