### ISSUE TITLE
Add API endpoint which allows the validator owner to change its username

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#1256]
We already provide this feature through the frontend, however, with an API, clients like Rocket Pool can sign and push the request directly through their node.

![chrome_PIYR0Dnzxf](https://user-images.githubusercontent.com/26490734/156791988-4238374c-9ee3-4ace-a210-6b7dd0caf9a0.png)

**Comment by Buttaa** [comment]
MEW sigs be fixed: https://github.com/gobitfly/eth2-beaconchain-explorer/issues/1220

**Comment by uwuforever** [comment]
Bump. Right now we're just using the nickname form's handler, but we would prefer a proper API.

**Comment by axljoker03** [comment]
thanks
