### ISSUE TITLE
Income report is not matching income of validator

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#1258]
The income for date value is almost always lower by a very small amount than the end of date balance for that day minus the end of date balance for the previous day.

For example, random validator looking at August 12th: 34.02711 - 34.02175 = 0.00536 which is higher than the income for the day of 0.00534.

https://www.beaconcha.in/rewards?validators=10987&currency=eur&days=1628568000-1628827199

**Comment by HPlumley** [comment]
Hi @Buttaa, I think you've come across the bug I reported here: #1179
