### ISSUE TITLE
Add validator index  and status to eth1+eth2 deposit page

### ISSUE THREAD

**Issue by handelaar2** [gobitfly/eth2-beaconchain-explorer#126]
For analysis of the validators it is helpful to display the **validators index**.

Currently the eth1+eth2 deposit page only show the pubkey.
If there is still room left on the page. please add the index.

If possible, also add the "Eth2 validator state" on the Eth2_deposit_page
(it is already there own the Eth1_deposit_page)
![2020-06-15_15-19-33](https://user-images.githubusercontent.com/28559038/84662300-ed64b780-af1b-11ea-9bd3-edd77aed2563.png)

**Comment by guybrush** [comment]
There are eth1-deposits where the corresponding validator does not have an index yet (not yet in the pending-queue, or activated, or in general not seen by eth2 yet).

We can add the validator-index to the eth2-deposits though.
