### ISSUE TITLE
Can't unsubscribe client notification

### ISSUE THREAD

**Issue by xanatos** [gobitfly/eth2-beaconchain-explorer#1304]
In the https://beaconcha.in/user/ethClients page, if I have subscribed to a client notification, and I try to unsubscribe, the change won't be saved. There doesn't seem to be a way to unsubscribe. Note that it seems that the page auto-saves the changes, so if you click a checkbox to subscribe, it is immediately saved, while if you click to unsubscribe the change isn't saved correctly.

**Comment by qu0b** [comment]
The UI seems to work fine for me. Would it be possible for you go give us more details such as console logs etc.

**Comment by xanatos** [comment]
Using Chrome 100 on Windows: "Versione 100.0.4896.127 (Build ufficiale) (a 64 bit)" and/or Ede: "Versione 101.0.1210.32 (Build ufficiale) (64 bit)" (I know that they are both "chromium" inside). I'm using an Italian computer if it is important.

Just tested if there is the same problem if I use Chrome + the Incognito Mode (so that all the extensions are disabled) and the problem remains.

The only two errors (and technically they are warnings) I get are:

DevTools failed to load source map: Could not load content for https://beaconcha.in/bundle/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
112 The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

The 112 is because the second warning "spawns" 112 times

**Comment by xanatos** [comment]
Just checked and the POST to https://beaconcha.in/user/notifications/unsubscribe?filter=teku&event=eth_client_update is done and the return value is 200, so it is a backend problem and/or account corruption

**Comment by qu0b** [comment]
Okay thank you for the update, we are looking into it

**Comment by qu0b** [comment]
We've pushed an update, let us know if that helped and thanks for bringing up the issue.

**Comment by xanatos** [comment]
Works correctly thanks.
