### ISSUE TITLE
"Pools" chart is inaccurate leading to confusion about the size of entities

### ISSUE THREAD

**Issue by superphiz** [gobitfly/eth2-beaconchain-explorer#1325]
The chart at https://beaconcha.in/pools shows Lido controlling 30,520 validators on mainnet ([image for reference](https://i.ibb.co/92Pk79z/Screenshot-from-2022-05-07-11-37-32.png)), while other sources like [hilldoby](https://dune.com/hildobby/ETH2-Deposits) show Lido with 125,011 validators ([image](https://i.ibb.co/k84Bxn1/Screenshot-from-2022-05-07-11-39-29.png)) and [Rated](https://www.rated.network/e/Lido) shows Lido with 107,705 ([image](https://i.ibb.co/r4HHCSX/Screenshot-from-2022-05-07-11-40-54.png)). Because beaconcha.in is such a well-known source, this bad information causes significant confusion in the community when estimating the governance authority of any provider. For example, in [this exchange](https://i.ibb.co/Jxy0yRH/stefak2k.png) the commenter believes that Kraken is a larger provider than Lido because of data presented by beaconcha.in (Lido is currently operating 3x more validators than Kraken).

**Comment by Buttaa** [comment]
Using the deposit addresses from https://dune.com/queries/309548 should give us at least the correct deposits for Lido

Rocketpool's should be available once https://github.com/gobitfly/eth2-beaconchain-explorer/pull/1245 is merged into production

**Comment by Buttaa** [comment]
This was fixed a few weeks ago, and i forgot to update the issue. 
Please let me know if we missed something :)
