### ISSUE TITLE
Rocketscan Link

### ISSUE THREAD

**Issue by evilrobot-01** [gobitfly/eth2-beaconchain-explorer#1338]
Hey,

The Rocketscan link (on the Rocket Pool tab of the validator page) on https://prater.beaconcha.in does not point to the corresponding https://prater.rocketscan.io/ site, but rather the mainnet site resulting in a "Node operator not found".

It also seems that rocketscan.dev is now rocketscan,io so probably worth updating that at the same time.

**Comment by Buttaa** [comment]
hi @evilrobot-01 , this should work now https://prater.beaconcha.in/validator/9362ed9a037250584b0af6ca8fcbfcff06582ec5e8ff52bfa10938aeb4313c5541d58d95ec6477d25373c0ddf2309898#rocketpool
