### ISSUE TITLE
Wrong etherscan url on beaconchain.ropsten.ethdevops.io

### ISSUE THREAD

**Issue by markocuri** [gobitfly/eth2-beaconchain-explorer#1363]
On beaconchain.ropsten.ethdevops.io, if you go to _Eth1 data_ for block and click on _Block hash_ link, you will be redirected to https://goerli.etherscan.io/ instead of https://ropsten.etherscan.io/

**Comment by Buttaa** [comment]
> On beaconchain.ropsten.ethdevops.io, if you go to _Eth1 data_ for block and click on _Block hash_ link, you will be redirected to https://goerli.etherscan.io/ instead of https://ropsten.etherscan.io/

Hi, we don't maintain beaconchain.ropsten.ethdevops.io, but https://ropsten.beaconcha.in/

**Comment by markocuri** [comment]
Ah, I see. Closing it :)
