### ISSUE TITLE
Lighthouse branch update

### ISSUE THREAD

**Issue by shayanb** [gobitfly/eth2-beaconchain-explorer#1366]
I noticed that the Lighthouse branch hasn't been updated since Aug 25, 2020: https://github.com/gobitfly/eth2-beaconchain-explorer/tree/lighthouse

Is there any technical reason behind it? I see that https://lighthouse.beaconcha.in/ is fully sync so I assume the development is happening but maybe not open source?

**Comment by Buttaa** [comment]
> I noticed that the Lighthouse branch hasn't been updated since Aug 25, 2020: https://github.com/gobitfly/eth2-beaconchain-explorer/tree/lighthouse
> 
> Is there any technical reason behind it? I see that https://lighthouse.beaconcha.in/ is fully sync so I assume the development is happening but maybe not open source?

The current version of the explorer uses Lighthouse, so both point to the main website (beaconcha.in)

**Comment by shayanb** [comment]
Thanks @Buttaa .
Just to clarify, all the documentations and the main readme are detailing Prysm installation/integration, is it safe to assume all of them are outdated? 
If so, we can try to update the documentation as we figure out the updated process for Lighthouse.

**Comment by Buttaa** [comment]
> Thanks @Buttaa . Just to clarify, all the documentations and the main readme are detailing Prysm installation/integration, is it safe to assume all of them are outdated? If so, we can try to update the documentation as we figure out the updated process for Lighthouse.
> 
> Update: it seems that the docker-compose file and all other settings point to Prysm.

Yes, they are mostly outdated :(
(Feel free to open a PR!)
