### ISSUE TITLE
Address based validator index lookup doesn't work on Ropsten

### ISSUE THREAD

**Issue by barnabasbusa** [gobitfly/eth2-beaconchain-explorer#1369]
When trying to lookup validators based on their deposit address, the site doesn't find the validator indexes on ropsten.beaconcha.in. 

The lookup feature seems to be working fine on the dev build. https://beaconchain.ropsten.ethdevops.io/

**Comment by Buttaa** [comment]
> When trying to lookup validators based on their deposit address, the site doesn't find the validator indexes on ropsten.beaconcha.in.
> 
> The lookup feature seems to be working fine on the dev build. https://beaconchain.ropsten.ethdevops.io/

This seems to be only valid if the validator was recently deposited, otherwise it works fine for me. Could you confirm?

**Comment by barnabasbusa** [comment]
The address lookup in the search function seem to work for deposits, but the dashboard functionality seems to be non functional.

**Comment by Buttaa** [comment]
> The address lookup in the search function seem to work for deposits, but the dashboard functionality seems to be non functional.

Okay i see two issues

1. `https://beaconcha.in/dashboard` does not find any eth1 address like `0x390e190ce00a0c7a44f41506cfd7b3574489c10d`

2. Searching for the validator pub key via main search bar in the header takes a few seconds , like `0xa539c59e583a934324ff7317a2f627eae1dc7ad1dccca163906fc8807555365c0635ddf90496e46fdcf4ad1f20d82582`

**Comment by Athayde3586** [comment]
I don't understand how u r saying that the validator isn't responding

**Comment by Athayde3586** [comment]
And I'm right here

**Comment by Athayde3586** [comment]
I don't understand how u r saying that the validator isn't responding  these r my accounts

**Comment by Buttaa** [comment]
@barnabasbusa this should be fixed now, could you confirm?

**Comment by barnabasbusa** [comment]
The search bar seems to be working, and it indeed shows the correct validators, however the dashboard's search bar doesn't seem to be working still. Also the "notification" tab / add validator button doesn't seem to be able to handle deposit address, only able to handle validator number.

**Comment by Buttaa** [comment]
> The search bar seems to be working, and it indeed shows the correct validators, however the dashboard's search bar doesn't seem to be working still. Also the "notification" tab / add validator button doesn't seem to be able to handle deposit address, only able to handle validator number.

Could you please provide more info so we can try on our end?
What address are you entering on /dashboard? on ropsten or mainnet?

> Also the "notification" tab / add validator button doesn't seem to be able to handle deposit address, only able to handle validator number.

This was not part of the OP, could you create a seperate issue for that?
