### ISSUE TITLE
Include the number of active validators in `/api/v1/validators/queue` API response

### ISSUE THREAD

**Issue by remyroy** [gobitfly/eth2-beaconchain-explorer#1385]
The `/api/v1/validators/queue` API returns the number of validators in the activation and exit queues. Unfortunatly, that information is not enough to provide a remaining time on when the queues will clear. We also need to know how many active validators there are. The more active validators there are on the network, the faster these queues will clear. The formula is:

```python
def get_validator_churn_limit(state: BeaconState) -> uint64:
    """
    Return the validator churn limit for the current epoch.
    """
    active_validator_indices = get_active_validator_indices(state, get_current_epoch(state))
    return max(MIN_PER_EPOCH_CHURN_LIMIT, uint64(len(active_validator_indices)) // CHURN_LIMIT_QUOTIENT)
```

Some details on this can be found in [the specs](https://benjaminion.xyz/eth2-annotated-spec/phase0/beacon-chain/#get_validator_churn_limit).

For instance, right now with 404103 active Validators on mainnet, the validator_churn_limit is at 6 meaning there can be 1350 validators activating each day instead of the default 900 validators per day.

**Comment by remyroy** [comment]
This request only needs adding one field to that API response, the current number of active validators. It's a value that should be fairly easy to obtain.

**Comment by Buttaa** [comment]
Hi remy, this was fixed a while ago, but please re-open if you run into any issues!
