### ISSUE TITLE
KILN: validators stuck at pending

### ISSUE THREAD

**Issue by Maigre** [gobitfly/eth2-beaconchain-explorer#1388]
Hi,
i got two validators on KILN but **both are stuck at "pending"** on beaconchain.kiln.themerge.dev

The first is 0x91e1402614389046c68ffd8e18bfb29d6c4eab081fd3aeff7b0a4d2b9ed08054c2c74748f668ae5700aa5b68ee14f0f9
Has been slashed.
Activated at epoch 15992
Exited at epoch 16861

The second is 0x8b3cc6ae7cfd168560c82ef6203e2f05afe001365a5c5b78f45c5c87f15a362c60d1b6ac0757214d010696fe0e87bbdd
Is still validating
Activated at epoch 17061

I confirmed both status using my CL REST Api.

Any help ? 
I am happy to help test the merge but, having few to no indicators of my test validators status is a bit (cue)cumbersome.

Thanks !
Best,

**Comment by Buttaa** [comment]
Hi, we don't maintain beaconchain.kiln.themerge.dev. 
Please reach out to devs in the R&D discord
