### ISSUE TITLE
Need help on simulating on beacon

### ISSUE THREAD

**Issue by zsharifian** [gobitfly/eth2-beaconchain-explorer#1414]
Hello to all
For my thesis work, I need to run Beacon on a some lab network nodes in my university (by defining the desired delay on each node), and of course apply some changes on it. I also need to have network view. Can anyone guide me?

Regard

**Comment by Buttaa** [comment]
> Hello to all For my thesis work, I need to run Beacon on a some lab network nodes in my university (by defining the desired delay on each node), and of course apply some changes on it. I also need to have network view. Can anyone guide me?
> 
> Regard

Hi
You are better of asking for help in the [ethstaker discord ](https://discord.io/ethstaker)

**Comment by zsharifian** [comment]
> > Hello to all For my thesis work, I need to run Beacon on a some lab network nodes in my university (by defining the desired delay on each node), and of course apply some changes on it. I also need to have network view. Can anyone guide me?
> > Regard
> 
> Hi You are better of asking for help in the [ethstaker discord ](https://discord.io/ethstaker)

Hi, 
Thank you very much for your advice
I have tried several times to join ethstaker discord separately and also through your invitation link, but unfortunately something is wrong
Is there any other way to get help?
