### ISSUE TITLE
Add Notification for offline validators

### ISSUE THREAD

**Issue by apache3333** [gobitfly/eth2-beaconchain-explorer#1415]
Hello!
Great work!
Wondering if you could add a notification for when a validator goes offline? 
Offline meaning when a validator misses _x_ amount of attestations in a row
Anyway would be handy...
Cheers,
G

**Comment by Buttaa** [comment]
> Hello! Great work! Wondering if you could add a notification for when a validator goes offline? Offline meaning when a validator misses _x_ amount of attestations in a row Anyway would be handy... Cheers, G

Hi, we already have this on our to-do list :)
Closing the issue, feel free to re-open if necessary
