### ISSUE TITLE
Validator wrongly labeled as member of coinbase validator pool

### ISSUE THREAD

**Issue by ieggel** [gobitfly/eth2-beaconchain-explorer#1421]
Hi,
A validator is wrongly shown as a member of a coinbase validator pool. Actually that particular validator is not a member of any pool. Are you aware of this bug?

**Comment by InvisibleSymbol** [comment]
Could you share the pubkey/index of the validator in question? Tagging is done automatically and as coinbase refuses to publicize their data, it's not perfect. I can look into fixing your case.

**Comment by ieggel** [comment]
Hi. I prefer not want to share this info publicly, so i contacted butta (maybe it's you ;) ?) on Discord. So i guess you should be in possession of all necessary info. Thank you :)
