### ISSUE TITLE
Validator Income History -> Deposit counts as income

### ISSUE THREAD

**Issue by FloHeld** [gobitfly/eth2-beaconchain-explorer#1434]
Hi,

Validator: 40870
Date Range: 01/12/2020 - 31/12/2020

[Ethereum 2.0 Beaconchain Explorer - Ethereum Validator Rewards - beaconcha.in - 2022 (2).pdf](https://github.com/gobitfly/eth2-beaconchain-explorer/files/9168991/Ethereum.2.0.Beaconchain.Explorer.-.Ethereum.Validator.Rewards.-.beaconcha.in.-.2022.2.pdf)

**Comment by Buttaa** [comment]
Hi, we are aware of this issue and it's in our backlog :)
