### ISSUE TITLE
Untracked metric: activation/exit queue rate

### ISSUE THREAD

**Issue by nixorokish** [gobitfly/eth2-beaconchain-explorer#1448]
The number of validators allowed to enter or exit the beaconchain per day is determined by the churn limit:
https://github.com/ethereum/consensus-specs/blob/dev/specs/phase0/beacon-chain.md#get_validator_churn_limit

Current number of validators / churn limit = number of validators allowed to exit per epoch, rounded down to the nearest whole number. * 225 (# epochs in a day) = number of validators allowed to enter or exit per day.

e.g. currently:
411,320 validators / 65536 = 6.28, rounded down to 6 * 225, 1350 or 43200 ETH allowed to enter/exit per day.

No dashboards currently track this rate - would be great if beaconcha.in could publish it.

**Comment by remyroy** [comment]
Related to #1385

**Comment by Buttaa** [comment]
This should be on our upcoming landing page.!
