### ISSUE TITLE
`ExecutionPayload` incompatible `BaseFeePerGas` type

### ISSUE THREAD

**Issue by mkykadir** [gobitfly/eth2-beaconchain-explorer#1496]
Explorer [type](https://github.com/gobitfly/eth2-beaconchain-explorer/blob/63287215ffad8e7d2a1318271bf42391b0e35757/types/exporter.go#L150) for `BaseFeePerGas` is `uint64`, but the consensus specification [states](https://github.com/ethereum/consensus-specs/blob/dev/specs/bellatrix/beacon-chain.md#executionpayload) it should be `uint256`. Thus, Prysm [implementation](https://pkg.go.dev/github.com/prysmaticlabs/prysm/v3@v3.0.0-rc.2/proto/engine/v1#ExecutionPayload) returns a byte array of size 32, which we need it to be parsed into `uint64` to parse a bellatrix block.

**Comment by Buttaa** [comment]
Hi kadir! 

Just a quick heads up that i have added this to our v2 API backlog.

**Comment by Buttaa** [comment]
Hi @mkykadir 

After rethinking this, it is easier to work with the current return value. The exception is when, as you described, one also wants to interact simultaneously with Prysm. We don't plan to add support for prysm in the foreseeable future, thus, we don't plan to add support for this in v2 either.
