### ISSUE TITLE
"Effectiveness" is calculated from what length of time?

### ISSUE THREAD

**Issue by JamesCropcho** [gobitfly/eth2-beaconchain-explorer#1500]
On the Android app's Dashboard is a percentage metric called Effectiveness.

From what length of time is it calculated? (For example: "from the past 10 minutes," "from the past hour," etc.)

Thank You,
James

P.S.: Please pardon me, for there is a duplicate issue at https://github.com/gobitfly/eth2-beaconchain-explorer-app/issues/116. I am reposting here because I worry that the original location of my question is not the proper one.

**Comment by Buttaa** [comment]
> On the Android app's Dashboard is a percentage metric called Effectiveness.
> 
> From what length of time is it calculated? (For example: "from the past 10 minutes," "from the past hour," etc.)
> 
> Thank You, James
> 
> P.S.: Please pardon me, for there is a duplicate issue at [gobitfly/eth2-beaconchain-explorer-app#116](https://github.com/gobitfly/eth2-beaconchain-explorer-app/issues/116). I am reposting here because I worry that the original location of my question is not the proper one.

Staking effectiveness is based on the last 100 epochs.
