### ISSUE TITLE
genesis block root and state root are incorrect

### ISSUE THREAD

**Issue by djrtwo** [gobitfly/eth2-beaconchain-explorer#152]
beaconcha.in reports the Altona genesis block root and state root incorrectly -- https://altona.beaconcha.in/block/0

Correct values can be found in the `altona` repo -- https://github.com/goerli/altona/tree/master/altona

**Comment by guybrush** [comment]
Actually we have 2 genesis blocks, you can find them by looking at the last page on https://altona.beaconcha.in/blocks

- https://altona.beaconcha.in/block/9e2ffe8ab9316e03e45409eaaffab10cf02e1b60e609276113e07240d4a31b7a
- https://altona.beaconcha.in/block/83189eee8cf84f967786245c27aee2681d5b66e1750cc79c1140199b9cd9ee3b

Not sure why we have 2 genesis blocks yet.

**Comment by djrtwo** [comment]
weird!
