### ISSUE TITLE
FR: Historical graffiti wall data

### ISSUE THREAD

**Issue by benv666** [gobitfly/eth2-beaconchain-explorer#1524]
Currently it is not possible to retrieve data of pixels that have been overwritten.
However, while contemplating making a timelapse video of the Graffiti Wall I realized that this would be needed.
(otherwise it will only show the drawing of the current state, which would skip any "turf wars" that might have happened)

So for this feature request, please implement an API endpoint to retrieve the historical pixeldata.
This could be an option to the current graffitiwall API operation. Bonus point when first implementing https://github.com/gobitfly/eth2-beaconchain-explorer/issues/1523 so we can focus on specific areas.

**Comment by Buttaa** [comment]
Hi ben, currently we don't have any resources for this integration. If you ever open a PR for it, we're happy to merge it
