### ISSUE TITLE
Aggregation bits shown in attestation is missing some bits

### ISSUE THREAD

**Issue by NIC619** [gobitfly/eth2-beaconchain-explorer#1537]
- Last byte of each line of aggregation bits is missing 1 bit (only 7 bits) and totally 3 bits are missing. This results in only 203 validators in a committee while there's currently about 206 validators in a committee:
![截圖 2022-09-07 下午11 24 51](https://user-images.githubusercontent.com/17670147/188917912-1fdca115-b4eb-4550-ab4d-b8f4e0287319.png)

- And few attestations are showing only 1 bit at the end of each line of aggregation bits:
![截圖 2022-09-07 下午11 24 56](https://user-images.githubusercontent.com/17670147/188917999-def232b4-ddcf-4415-a482-39c61f1c9d99.png)

Pictures took from attestations in block 4642490:
https://beaconcha.in/block/4642490#attestations

**Comment by Buttaa** [comment]
This was fixed in the latest release, please re-open the issue if not  :)
