### ISSUE TITLE
Error 502 whilst looking up validator

### ISSUE THREAD

**Issue by kaiwetlesen** [gobitfly/eth2-beaconchain-explorer#1541]
We received an error 502 whilst attempting to look up our validator. It has happened before and mysteriously resolved itself. Could it be that BeaconCha.in reaches out to the validator itself? This occurs both when searching for our validator by index and by key, and also occurs with a direct link: https://prater.beaconcha.in/validator/335916
![image](https://user-images.githubusercontent.com/9599381/189242619-7cd83878-72c5-48a3-a546-4d38e068be3b.png)

**Comment by qu0b** [comment]
we've pushed a fix let us know if that helped be74df63fb13f4f9afcba256ae4d40a3dbf9ba64

**Comment by kaiwetlesen** [comment]
@qu0b that did it! Thank you.
