### ISSUE TITLE
attestationeffectiveness and attestationefficiency same result

### ISSUE THREAD

**Issue by Dark345** [gobitfly/eth2-beaconchain-explorer#1543]
Hello

querying [/attestationefficiency](https://beaconcha.in/api/v1/validator/1/attestationefficiency) and [/attestationeffectiveness](https://beaconcha.in/api/v1/validator/1/attestationeffectiveness) is giving out same result -> _attestation_efficiency_

**Comment by Buttaa** [comment]
> Hello
> 
> querying [/attestationefficiency](https://beaconcha.in/api/v1/validator/1/attestationefficiency) and [/attestationeffectiveness](https://beaconcha.in/api/v1/validator/1/attestationeffectiveness) is giving out same result -> _attestation_efficiency_

Hi, we will discontinue /attestationefficiency soon, since both return the same, as you mentioned.
