### ISSUE TITLE
Slot links on site go to `/block/{slot}`

### ISSUE THREAD

**Issue by dickmanben** [gobitfly/eth2-beaconchain-explorer#1549]
Looks like links to slots go to `/block` which now shows the block with a block number equal to that slot number.

<img width="542" alt="Screen Shot 2022-09-13 at 10 15 38 AM" src="https://user-images.githubusercontent.com/8403969/189925004-8b9eb17e-7104-4d62-9234-fb0acd8d16ed.png">

<img width="502" alt="Screen Shot 2022-09-13 at 10 17 03 AM" src="https://user-images.githubusercontent.com/8403969/189925377-07df355e-34b5-490d-b3fe-53bb158504ec.png">

**Comment by Buttaa** [comment]
@dickmanben It depends on the view. Blocks point to specific slots and vice versa. 
Could you post an example where you think it's wrong?

**Comment by dickmanben** [comment]
Click on the slot in the banner 
<img width="920" alt="Screen Shot 2022-09-13 at 10 25 06 AM" src="https://user-images.githubusercontent.com/8403969/189927393-c32c5658-4e71-4ac1-ae8f-144efbe8897a.png">

**Comment by Buttaa** [comment]
> Click on the slot in the banner <img alt="Screen Shot 2022-09-13 at 10 25 06 AM" width="920" src="https://user-images.githubusercontent.com/8403969/189927393-c32c5658-4e71-4ac1-ae8f-144efbe8897a.png">

Thanks, we pushed a fix
