### ISSUE TITLE
 monitoring endpoint URL should be in quotation marks

### ISSUE THREAD

**Issue by FabianSchuessler** [gobitfly/eth2-beaconchain-explorer#1564]
![Unbenannt](https://user-images.githubusercontent.com/10107422/190852888-1bf08551-af0d-4e14-bf21-2f2c401d98ad.PNG)

The monitoring endpoint URL should be in quotation marks because some terminals might cut off after the special characters "&" or "?".

**Comment by recy21** [comment]
Thank you for your interest in our project.
Fixed with: https://github.com/gobitfly/eth2-beaconchain-explorer/commit/9152f1f057ed2156593c6b00f2cfc451026ce7bd
Will be part of next release
