### ISSUE TITLE
Wrong validator_attestation_missed notification

### ISSUE THREAD

**Issue by sbuljac** [gobitfly/eth2-beaconchain-explorer#1568]
I received email "Your validator(s) missed an attestation" but after checking it on beaconchain attestation for slot specified was submitted on time.

**Comment by StarryJapanNight** [comment]
Same issue.

**Comment by Buttaa** [comment]
Both issues were fixed. 
The attestation effectiness formula also changed slightly based on https://www.attestant.io/posts/defining-attestation-effectiveness/
