### ISSUE TITLE
Altona input data deposited to onyx

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#157]
1. Shows correctly that it has an invalid sig but displays wrong index number/block proposals/Attestation

2. Can't find the validator through the search bar
![firefox_2020-07-04_09-32-01](https://user-images.githubusercontent.com/26490734/86507541-43b96d80-bdd9-11ea-98f8-374fd11fdd7c.png)

https://beaconcha.in/validator/adbc3f63976d55ab7ade701b450824bcb74b35b6d4c242b802a61100f4048749132040a311c3397cd4d3731dbe01fcdd

**Comment by guybrush** [comment]
Fixed by  7d77428
