### ISSUE TITLE
`api/v1/validator/stats/{index}` returns wrong number of `missed_blocks`

### ISSUE THREAD

**Issue by nalepae** [gobitfly/eth2-beaconchain-explorer#1572]
With the validator index `321403`, the UI shows:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/4943830/191693354-7748f62b-4e01-458a-b09d-f7af91e76d81.png">

(Which seems to be the truth)

However, all fields `missed_blocks` in the response of the following requests equal to `0`. 
```
curl -X 'GET' \
  'https://beaconcha.in/api/v1/validator/stats/321403' \
  -H 'accept: application/json'
```

(`missed_attestations` seems also to be inaccurate)

**Comment by recy21** [comment]
Fixed in [v1.22.0](https://github.com/gobitfly/eth2-beaconchain-explorer/releases/tag/v1.22.0)
