### ISSUE TITLE
sepolia.beaconcha.in not working

### ISSUE THREAD

**Issue by nalepae** [gobitfly/eth2-beaconchain-explorer#1573]
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/4943830/191697087-4029a7a3-65bd-4d83-9c36-6fdedc4e49a2.png">
(It uses to work a few weeks ago)

**Comment by Buttaa** [comment]
> <img alt="image" width="1501" src="https://user-images.githubusercontent.com/4943830/191697087-4029a7a3-65bd-4d83-9c36-6fdedc4e49a2.png">
> 
> (It uses to work a few weeks ago)

Hi, we dropped sepolia support few weeks ago. We might revive our sepolia explorer soon.

**Comment by lightclient** [comment]
@Buttaa why did you drop support? Sepolia is the new preferred chain for developers to use to test dapps, would be very nice to have a beacon explorer like the other testnets.
