### ISSUE TITLE
Request a missed attestation threshold for notifications

### ISSUE THREAD

**Issue by superphiz** [gobitfly/eth2-beaconchain-explorer#1577]
Missed attestations do occasionally occur and they're not a high concern, but knowing when a threshold of missed attestations has occurred can provide data for rapid response without notification fatigue. I'm requesting a "missed attestation threshold" (maybe a default of three consecutive missed attestations) to notify the user when it's likely that their validator is down. I'm not sure if the number needs to be user-configurable, maybe a simple toggle for "notify me after 3 missed attestations".

**Comment by Buttaa** [comment]
hi, It's on our todo -- duplicate of https://github.com/gobitfly/eth2-beaconchain-explorer/issues/1158

**Comment by superphiz** [comment]
Thanks Butta!
