### ISSUE TITLE
FR: Can the Balance Change be listed in Twei so that we can see the number without having to mouse over. 

### ISSUE THREAD

**Issue by htimsk** [gobitfly/eth2-beaconchain-explorer#1579]
Can the Balance Change be listed on the Validator History panel in Twei (terawei) so we can see the number without having to mouse over it? 

See: https://imgur.com/a/B5z7jaT

**Comment by Buttaa** [comment]
We changed it to Gwei a long time ago, I hope you like that one ... :)
