### ISSUE TITLE
FR: API handler to return original epoch for a given validator index

### ISSUE THREAD

**Issue by Eth2User** [gobitfly/eth2-beaconchain-explorer#1580]
I am trying to use beaconcha.in to track a validators rewards over time.

I would like to be able to GET the first epoch that a validator was active for.

I think that this could be added as a new Validator api handler that could look like:
/api/v1/validator/{indexorPubkey}/initialepoch

The command would effectively boil down to something like:
`SELECT epoch FROM validator_set WHERE validatorindex={indexorPubKey} ORDER BY epoch ASC LIMIT 1`

My initial thought is that the only changes need to be a new handler in main.go and changes in api.go that could look like the following:

```
// ApiValidator godoc
// @Summary Get up to 100 validators
// @Tags Validator
// @Produce  json
// @Param  indexOrPubkey path string true "Up to 100 validator indicesOrPubkeys, comma separated"
// @Success 200 {object} string
// @Router /api/v1/validator/{indexOrPubkey}/initialepoch [get]
func ApiValidatorInitialEpoch(w http.ResponseWriter, r *http.Request) {

	w.Header().Set("Content-Type", "application/json")

	j := json.NewEncoder(w)
	vars := mux.Vars(r)
	maxValidators := getUserPremium(r).MaxValidators

	queryIndices, err := parseApiValidatorParam(vars["indexOrPubkey"], maxValidators)
	if err != nil {
		sendErrorResponse(j, r.URL.String(), err.Error())
		return
	}

	rows, err := db.ReaderDb.Query("SELECT epoch FROM validator_set WHERE validatorindex= ANY($1) ORDER BY epoch ASC LIMIT 1", pq.Array(queryIndices))
	if err != nil {
		sendErrorResponse(j, r.URL.String(), "could not retrieve db results")
		return
	}
	defer rows.Close()

	returnQueryResults(rows, j, r)
}
```

Please correct me if theres anything incorrect here.
Great work on this project so far and can't wait to watch it grow!

**Comment by Buttaa** [comment]
Hi!
This will be part of our v2 API later this year
