### ISSUE TITLE
FR: API handler to return balancehistory for > 100 epochs for only a single validator index

### ISSUE THREAD

**Issue by Eth2User** [gobitfly/eth2-beaconchain-explorer#1581]
I would like to see a balancehistory response with greater than 100 epochs.
To maintain performance, the trade-off would be that this request will be limited to a single validator index.

bigTable.go has a function `GetValidatorBalanceHistory` that I think could be re-used in api.go.

I have a sample change, although there may be oversights here. Could a change like this be as simple as the following?:

```
// ApiValidator godoc
// @Summary Get the balance history (last 10,000 epochs) of ONLY a single validator
// @Tags Validator
// @Produce  json
// @Param  indexOrPubkey path string true "Check for single validator"
// @Success 200 {object} string
// @Router /api/v1/validator/{indexOrPubkey}/balancehistorysinglevalidator [get]
func ApiValidatorBalanceHistorySingleValidator(w http.ResponseWriter, r *http.Request) {

	w.Header().Set("Content-Type", "application/json")

	j := json.NewEncoder(w)
	vars := mux.Vars(r)

	queryIndices, err := parseApiValidatorParam(vars["indexOrPubkey"], 1)
	if err != nil {
		sendErrorResponse(j, r.URL.String(), err.Error())
		return
	}

	history, err := db.BigtableClient.GetValidatorBalanceHistory(queryIndices, services.LatestEpoch(), 10001)
	if err != nil {
		sendErrorResponse(j, r.URL.String(), "could not retrieve db results")
		return
	}

	type responseType struct {
		Balance          uint64 `json:"balance"`
		EffectiveBalance uint64 `json:"effectivebalance"`
		Epoch            uint64 `json:"epoch"`
		ValidatorIndex   uint64 `json:"validatorindex"`
		Week             uint64 `json:"week"`
	}
	responseData := make([]*responseType, 0, len(history)*10001)

	for validatorIndex, balances := range history {
		for _, balance := range balances {
			responseData = append(responseData, &responseType{
				Balance:          balance.Balance,
				EffectiveBalance: balance.EffectiveBalance,
				Epoch:            balance.Epoch,
				ValidatorIndex:   validatorIndex,
				Week:             balance.Epoch / 1575,
			})
		}
	}

	sort.Slice(responseData, func(i, j int) bool {
		if responseData[i].Epoch != responseData[j].Epoch {
			return responseData[i].Epoch > responseData[j].Epoch
		}
		return responseData[i].ValidatorIndex < responseData[j].ValidatorIndex
	})

	response := &types.ApiResponse{}
	response.Status = "OK"

	response.Data = responseData

	err = j.Encode(response)

	if err != nil {
		sendErrorResponse(j, r.URL.String(), "could not serialize data results")
		return
	}
}
```

Eventually, Beaconcha.in could support this as a part of the one endpoint:
/api/v1/validator/{indexOrPubkey}/balancehistory
Where the app will check if queryIndices.len == 1

However, for the sake of time to market, a new endpoint could be implemented that could look like:
/api/v1/validator/{indexOrPubkey}/balancehistorysinglevalidator

I have not had the chance to test any changes locally yet. Are there any limits that are hit by GetValidatorBalanceHistory that would prevent it from pulling 10,000 epochs?
It looks like the UI has access to 1 weeks' worth of epochs (1,575 epochs) via APIDashboardDataBalance function. So if there is a limit that is hit, then an api equivalent that returns at least 1,575 epochs would be acceptable, although more epochs would be better. 
Please share your thoughts!
Thanks

**Comment by Eth2User** [comment]
Thanks for following up here. I would think that the existing functionality for /validator/{validatorindex}/balancehistory would cover #1221 since it can return some of the history for a particular address. 
I would like to expand on this to upgrade the handler so that it can return more than 100 epochs

**Comment by jliuu14** [comment]
+1 on this feature. It would also be nice to be able to specify which epoch or a range of epochs to grab from

**Comment by Buttaa** [comment]
hi, @Eth2User , @jliuu14 , this should work with the latest endpoint by adding the latest epoch, 

https://beaconcha.in/api/v1/docs/index.html#/Validator/get_api_v1_validator__indexOrPubkey__balancehistory
