### ISSUE TITLE
Why is there a time difference between the proposed block and transaction for an address?

### ISSUE THREAD

**Issue by 1shashijha1** [gobitfly/eth2-beaconchain-explorer#1583]
Why is there a time difference between the proposed block and transaction for an address?

https://beaconcha.in/address/a4c94a6091545e40fc9c3e0982aec8942e282f38#transactions

https://beaconcha.in/address/a4c94a6091545e40fc9c3e0982aec8942e282f38#blocks

do attach the community link!

**Comment by Buttaa** [comment]
https://beaconcha.in/address/a4c94a6091545e40fc9c3e0982aec8942e282f38#transactions

Displays the transactions that were sent from the address.

https://beaconcha.in/address/a4c94a6091545e40fc9c3e0982aec8942e282f38#blocks

Displays the proposed blocks (fee recipient)
