### ISSUE TITLE
Feature request: Public unauthenticated page to push signed validator messages to the network

### ISSUE THREAD

**Issue by uwuforever** [gobitfly/eth2-beaconchain-explorer#1593]
It would be nice to have an unauthenticated page to push signed messages onto the beacon chain P2P network, similar to "pushTx" raw transaction broadcast tools like https://etherscan.io/pushTx, just for validator/beacon chain messages instead of transactions.

This would be useful for users needing to voluntarily exit, set a withdrawal address, request a withdrawal, etc. Instead of requiring an account, it could authenticate requests by simply checking that each signed message is valid.

**Comment by Buttaa** [comment]
Hi, i added it to our to-do list! 

Broadcasting signatures for 

- Validator exit requests
- Converting 0x0 to 0x01 credentials
