### ISSUE TITLE
Is the version of the code on the main branch stable? 

### ISSUE THREAD

**Issue by FracaShaw-Alk** [gobitfly/eth2-beaconchain-explorer#1617]
I have followed the readme "Developing locally with docker" but I keep running into errors... I have started fixing the errors one by one but it feels like this repo is broken. Should I be using an other branch?

**Comment by Faithtosin** [comment]
@FracaShaw-Alk  Were you able to deploy the explorer? I'm also facing some issues getting the explorer container to work.

**Comment by FracaShaw-Alk** [comment]
@Faithtosin no I was not...

**Comment by Faithtosin** [comment]
@FracaShaw-Alk  What error are you getting? 

For me I get this error when I start the container with my config.
`Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.`
I have geth and prsym fully synced too, with postgres db and tables created
