### ISSUE TITLE
Incorrect transaction fee showing

### ISSUE THREAD

**Issue by cptblack1** [gobitfly/eth2-beaconchain-explorer#1620]
After the problems with Manifold MEV reporting proposals that didn't exist, the beaconcha.in app is showing those proposals in the transaction fee balance.

**Comment by Buttaa** [comment]
@cptblack1 as you said, it's a relay issue. We are using the relays' api to pull the data.

**Comment by cptblack1** [comment]
Thanks for getting back to me. I didn't think much could be done at your end, just thought I'd try.
