### ISSUE TITLE
Bug: Notifications (to email and mobile) for proposals have stopped firing

### ISSUE THREAD

**Issue by ianw11** [gobitfly/eth2-beaconchain-explorer#1627]
For my past two proposals, I have not received emails or push notifications.  My settings on the web app are to send email and push (and webhook, although I disable it but it keeps re-enabling itself). In mobile I also listen for proposals.

Unsure when this issue started, although I've definitely been missing notifications since the merge.

**Comment by Buttaa** [comment]
> For my past two proposals, I have not received emails or push notifications. My settings on the web app are to send email and push (and webhook, although I disable it but it keeps re-enabling itself). In mobile I also listen for proposals.
> 
> Unsure when this issue started, although I've definitely been missing notifications since the merge.

Could you make sure the notifications are enabled here? https://beaconcha.in/user/notifications 

![image](https://user-images.githubusercontent.com/26490734/197042194-47c94c8f-cf0f-43d5-9a47-0af2fcaebb43.png)
![image](https://user-images.githubusercontent.com/26490734/197042312-bc70322b-2f4c-4b2b-a689-c41cdd20ccac.png)

**Comment by ianw11** [comment]
Yes the first picture is the one where webhooks keep re-enabling themselves
In the second picture I have all but "validator offline" enabled

**Comment by Buttaa** [comment]
> Yes the first picture is the one where webhooks keep re-enabling themselves In the second picture I have all but "validator offline" enabled

I fail to reproduce it on my end; i keep receiving notifications for recently proposed blocks (as expected).
Could you try removing all validators and re-adding them and the same for the notification channels?

**Comment by recy21** [comment]
Outdated issue, please report again if the problem still persists.
