### ISSUE TITLE
beaconcha.in/pools webpage apr values and beaconcha.in api ethstore/latest apr values do not match

### ISSUE THREAD

**Issue by canbal99** [gobitfly/eth2-beaconchain-explorer#1633]
If I click on the webpage (https://beaconcha.in/pools), apr values displayed are:
APR31d = 5.69%
APR7d = 5.65%
APR1d = 5.56%
So minimum is APR1d and max is APR31d.

But if I use beaconcha.in api (curl -s https://beaconcha.in/api/v1/ethstore/latest), then apr values displayed are:
apr = 5.69% (exact value received 0.0568727525308009)
avgapr31d = 5.56% (exact value received 0.05557350389071258)
avgapr7d = 5.65% (exact value received 0.05651822300819035)

avgapr7d is equal to APR7d.
APR1d is equal to avgapr31d.
APR31d is equal to apr(probably one day).

So I think there is a problem with webpage's or api's labeling for 1d and 31d.

**Comment by Buttaa** [comment]
> If I click on the webpage (https://beaconcha.in/pools), apr values displayed are: APR31d = 5.69% APR7d = 5.65% APR1d = 5.56% So minimum is APR1d and max is APR31d.
> 
> But if I use beaconcha.in api (curl -s https://beaconcha.in/api/v1/ethstore/latest), then apr values displayed are: apr = 5.69% (exact value received 0.0568727525308009) avgapr31d = 5.56% (exact value received 0.05557350389071258) avgapr7d = 5.65% (exact value received 0.05651822300819035)
> 
> avgapr7d is equal to APR7d. APR1d is equal to avgapr31d. APR31d is equal to apr(probably one day).
> 
> So I think there is a problem with webpage's or api's labeling for 1d and 31d.

Thanks, we will take a look

**Comment by Buttaa** [comment]
Thanks for reporting this issue, this was fixed, but please re-open if you still run into the issue

**Comment by canbal99** [comment]
Checked again.
Now values match.
Thanks...
