### ISSUE TITLE
Failed to publish metrics to external metrics service. Response code 400

### ISSUE THREAD

**Issue by maddhaters** [gobitfly/eth2-beaconchain-explorer#1636]
I have added the `--metrics` to my Teku beacon and consensus configurations but seeing the following error every 6 blocks or so. 

```
Failed to publish metrics to external metrics service. Response code 400
```
I am seeing most of the data in the app under monitoring, save for Machine under CPU, Disk Usage under Disk, Validators under Sync. 

<img src="https://user-images.githubusercontent.com/114345531/198882275-3542d57a-430b-4395-ae3b-d130efd89c57.png" height=800 width=400/>

**Comment by maddhaters** [comment]
how did you determine the issue is with the beacon chain and not the validator based on the errors?

**Comment by brddd** [comment]
> how did you determine the issue is with the beacon chain and not the validator based on the errors?

Oops, I meant to say, my validator is not currently giving any errors.   It has in the past with the same HTTP 400 code from the https://beaconcha.in server.    Once I started changing the `—monitoring-endpoint-period` values it varied which one had the error.    The default is 60 seconds for lighthouse.    Also during updates and how long they have been down for, one of them starts sending metrics first, meaning it can vary which one succeeds and which one fails.

Is there any rate-limiting for this API on beaconcha.in?   All had been fine until early October, my set up has not changed and then I started noticing an error every 60 seconds in the logs.    Strangely, monitoring data seems ok in the iOS beaconcha.in app.

**Comment by jrray** [comment]
I am also seeing 400 errors. On https://beaconcha.in/user/settings#api I see that I am way over budget for my monthly requests. Not sure if related, but guessing there is a connection. When does this reset? I'm running a rocketpool node and not doing any extra API calls on my own.

![image](https://user-images.githubusercontent.com/3501/199620465-992dbb5c-444d-48ff-817a-5574df672cd0.png)

**Comment by brddd** [comment]
> I am also seeing 400 errors. On https://beaconcha.in/user/settings#api I see that I am way over budget for my monthly requests. Not sure if related, but guessing there is a connection. When does this reset? I'm running a rocketpool node and not doing any extra API calls on my own.
> 
> ![image](https://user-images.githubusercontent.com/3501/199620465-992dbb5c-444d-48ff-817a-5574df672cd0.png)

Good catch!  Mine are also at 14% for daily and 242% for monthly.   I’m just using the recommended settings for lighthouse which sends metrics every 60 seconds each for the validator and beacon.   I’ve even reduced the time to be every 120 seconds.

Perhaps this send metrics API call should not count towards your API free allocation.

**Comment by maddhaters** [comment]
I'm not sure if that's the issue just looking at my usage
![image](https://user-images.githubusercontent.com/114345531/199627446-d5e5baf2-e5b6-4d26-a0b7-3a771fd0faba.png)

**Comment by jrray** [comment]
After increasing the report interval (teku: `--metrics-publish-interval=<INTEGER>`) to over 120 for both the beacon and validator process I've seen it go more than 10 minutes between 400 errors.

It's a shame the clients don't offer to show the body of the response because the server does send back a short string to categorize the reason for the failure, e.g.: https://github.com/gobitfly/eth2-beaconchain-explorer/blob/c7d4db54da9cecde2359acbf0067d797899fed3b/handlers/api.go#L2130

**Comment by jrray** [comment]
> one process per machine per user each minute is allowed.

I believe I understand now what is going on. If the clients are advertising their PIDs when publishing metrics, both my beacon and validator have PID 1 inside their respective containers. No matter what interval is being used, after one container publishes metrics, then the other container has to wait 60 seconds before it can publish successfully.

I configured my two processes with different prime number intervals: 127 and 131. After startup I was seeing 400 errors regularly, but the errors stopped after about 15 minutes. This is how long it took for the two processes to start reporting with at least 60 seconds delay between them. Now I'm seeing the occasional 400 error in one or the other process when they come into phase with each other and violate the 60 second delay.

**Comment by manuelsc** [comment]
Our free tier only supports one machine. The errors you see are expected and normal if you are running more machines on a free tier like seen on your screenshot. You can upgrade your beaconcha.in account here https://beaconcha.in/premium for more machine support.

**Comment by brddd** [comment]
> Our free tier only supports one machine. The errors you see are expected and normal if you are running more machines on a free tier like seen on your screenshot. You can upgrade your beaconcha.in account here https://beaconcha.in/premium for more machine support.

That’s not the case for me.   I am only monitoring one machine, but I am also on the “goldfish” tier which supports two machines.    I didn’t get 400 errors until early October with no changes in my setup.

**Comment by jrray** [comment]
> I configured my two processes with different prime number intervals: 127 and 131.

With this scheme I am getting a monitoring_machine_offline notification every 12.9 hours.

**Comment by recy21** [comment]
Outdated issue, please report again if the problem still persists.
