### ISSUE TITLE
Error deploying explorer docker image

### ISSUE THREAD

**Issue by Faithtosin** [gobitfly/eth2-beaconchain-explorer#1638]
I get this error when I start the container with my config.

`Caught SIGILL in blst_cgo_init, consult <blst>/bindinds/go/README.md.`

I have geth and prsym fully synced too, with postgres db migrated.

I get this same error with the the official docker image and using the docker compose on the master branch.

**Comment by recy21** [comment]
Thank you for your interest in our project.

Lately we facing the SIGILL error (1 out of 3 commits) when building with GitHub too. Still not sure why it's there, but just rebuilding solves the problem, so didn't invested research into it till now.

But anyway, currently we only support Lighthouse & Erigon.
Explorer will probably run with others as well (e.g. Geth & Prysm), but with that there will be some parts that don't work properly, so officially speaking: **Lighthouse & Erigon is mandatory atm.**
