### ISSUE TITLE
Dashboard Proposals List View Shows Incorrect and Duplicate Date/Times and Misses Second Proposal on Same Day

### ISSUE THREAD

**Issue by metanull-operator** [gobitfly/eth2-beaconchain-explorer#1649]
**Describe the bug**

On dashboard screen, proposals tab, table list view of proposals, a few different types of errors:

1. Date/time shown on "Date" column is wrong. All of my dates say "X days 4 hrs ago". 

Screenshots from my Goerli dashboard.

![image](https://user-images.githubusercontent.com/54516310/200398211-00e6b48c-56b0-4472-815c-d0bfa0e6304b.png)

But if you look at the proposals on the validator page, the date/time is incorrect.  They aren't all exactly "X days 4 hrs ago". In fact, the X days is also incorrect.

![image](https://user-images.githubusercontent.com/54516310/200398357-04efe770-b7ff-44d3-9264-f010dffc429a.png)

![image](https://user-images.githubusercontent.com/54516310/200398408-22a6e3a4-4e4d-44e7-b8a4-db5e4c07b739.png)

![image](https://user-images.githubusercontent.com/54516310/200398447-fdbbbef4-38bd-426b-9dc1-88ed05d4ae9a.png)

It also appears that the 2nd and 3rd date/time on that list is identical. Oddly, this is also the case on my mainnet dashboard. The 2nd and 3rd date/time always seems to be identical.

2. Also on my mainnet dashboard, a validator that had two proposals within 15-20 hours of each other only shows one proposal on the same screen being discussed.

**To Reproduce**
1. Go to 'Dashboard'
4. Click on 'Proposals' tab
5. Click on table/list view of proposals
6. See that dates aren't shown correctly.

**Expected behavior**
Proposal dates and times should be correct and multiple proposals from the same validator should show up in the list.

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Chrome
 - Version 106.0.5249.119

**Additional context**

**Comment by shayanb** [comment]
This issue still persist, looking at a validator like https://beaconcha.in/validator/270246

<img width="942" alt="Screenshot 2023-01-04 at 11 56 02 PM" src="https://user-images.githubusercontent.com/309108/210704766-23e9a753-3916-49b1-af0e-6d7bdb2e9980.png">


the chart above shows the proposals on Dec 15 and Dec 17, despite the blocks both being proposed on the 15th, around 5 and 8 pm EST respectively

<img width="951" alt="Screenshot 2023-01-04 at 11 56 16 PM" src="https://user-images.githubusercontent.com/309108/210704788-5689533b-d4d6-4563-a0e9-8a5553c297f7.png">

**Comment by recy21** [comment]
Thank you for your interest in our project.
This issue should be fixed already and I will close this topic.
Please feel free to create another issue if the error still exists for you.
