### ISSUE TITLE
Validator API returns different types

### ISSUE THREAD

**Issue by dsimog01** [gobitfly/eth2-beaconchain-explorer#1673]
For retrieving validator info from the validator API (.../api/v1/validator/), you get different response types depending on if you pass 1 validator key or several as arguments. If there are several validator pubkeys, response.data is an array, but in the other case it is just an object. For consistency, I would suggest returning always an array

**Comment by Buttaa** [comment]
This was fixed in our latest reelease :)

**Comment by recy21** [comment]
Thank you for your interest in our project.
Created an internal ticket, will update here if we have new information.

**Comment by dospore** [comment]
@recy21 has this been completed? am looking for issues I can contribute too?

**Comment by recy21** [comment]
@dospore yes, is completed in https://github.com/gobitfly/eth2-beaconchain-explorer/pull/1879

Thank you for your interest in our project.
If you already joined our Discord Server (https://discord.gg/pAFdjzMJ), you can contact me there, maybe we find some other issue for you.
