### ISSUE TITLE
unknown justified root" prefix=blockchain issue

### ISSUE THREAD

**Issue by YASHTHAKOR** [gobitfly/eth2-beaconchain-explorer#1714]
I am syncing with docker and almost at the end it gives this error

**To Reproduce**
1. clone the repo
2. after runner docker-compose up getting this error almost at the last moment of sync completion

**Expected behavior**
Could not compute head from new attestations" error="{hex address}: unknown justified root" prefix=blockchain

<img width="746" alt="Screenshot 2022-12-14 at 10 52 36" src="https://user-images.githubusercontent.com/14930173/207512820-9dec5748-95ff-409a-93e9-fcb162b358da.png">

**Screenshots**
attached

 - OS:ubuntu 20.02

**Comment by recy21** [comment]
Hey, this sounds to me like a Prysm issue not related to our repository/project. Maybe you should ask for help in the Prysm project? https://github.com/prysmaticlabs/prysm
