### ISSUE TITLE
`/api/v1/client/metrics` returns a  rate limit error if parsing of data fails

### ISSUE THREAD

**Issue by nflaig** [gobitfly/eth2-beaconchain-explorer#1746]
**Describe the bug**

`/api/v1/client/metrics` returns a rate limit error if parsing of data fails

**To Reproduce**

```
curl -X 'POST' 'https://beaconcha.in/api/v1/client/metrics?apikey={apikey}' -H 'accept: application/json' -d ''

{"status":"ERROR: metrics rate limit reached, one process per machine per user each minute is allowed.","data":null}
```

**Expected behavior**

Should return a error which indicates that the sent data is invalid., e.g. `Invalid JSON format in request body`

**Comment by Buttaa** [comment]
> **Describe the bug**
> 
> `/api/v1/client/metrics` returns a rate limit error if parsing of data fails
> 
> **To Reproduce**
> 
> ```
> curl -X 'POST' 'https://beaconcha.in/api/v1/client/metrics?apikey={apikey}' -H 'accept: application/json' -d ''
> 
> {"status":"ERROR: metrics rate limit reached, one process per machine per user each minute is allowed.","data":null}
> ```
> 
> **Expected behavior**
> 
> Should return a error which indicates that the sent data is invalid., e.g. `Invalid JSON format in request body`

@nflaig hi, are you using the API on two machines at the same time maybe?

**Comment by nflaig** [comment]
@Buttaa I check the source code, it is definitely related to invalid json as the error is thrown when unmarshaling fails, see [api.go line 2468](https://github.com/gobitfly/eth2-beaconchain-explorer/blob/688bb9d93365233b54ac416cd2823db6570598ae/handlers/api.go#L2468). The warning log message even says that parsing failed but the send error message talks about the rate limit

**Comment by qu0b** [comment]
@manuelsc it looks like the error message is misleading https://github.com/gobitfly/eth2-beaconchain-explorer/blob/5116fda3154237621a476278514bf939c36d8a4c/handlers/api.go#L2388-L2392

**Comment by manuelsc** [comment]
It's super misleading, we should change that.

**Comment by MauserBitfly** [comment]
Error message will be corrected with [PR 1875](https://github.com/gobitfly/eth2-beaconchain-explorer/pull/1875):
