### ISSUE TITLE
Beacon-chain size graph feature

### ISSUE THREAD

**Issue by ncitron** [gobitfly/eth2-beaconchain-explorer#175]
It would be nice to have a graph of the size of the beacon chain over time. Beaconscan has one (although it does not appear to be working). This feature could be useful down the line when new validators need to decide their hard drive requirements. I'd be happy to try an tackle this feature myself, but I'm not quite sure what the best way to calculate the chain size would be...

**Comment by SjonHortensius** [comment]
I think you should poll prysm or lighthouse to add this to their API. For example, lighthouse has [/node/health](https://lighthouse-book.sigmaprime.io/http/node.html#nodehealth) which seems like a good candidate

The alternative would require this explorer to have access to the datadir of the beacon node (which it doesn't necessarily have) or do some pretty random assumptions about the storage requirements of certain data

**Comment by guybrush** [comment]
We could expose grafana with node-exporter from nodes with running validators on it.

The thing is that this makes the explorer much less trivial to run. 

Not sure about this yet, if you come up with some cool way to solve it we are definitely open for suggestions and/or PRs!

**Comment by ncitron** [comment]
I asked over at Prysm discord what they thought about adding a chain size API endpoint, but they said that since the chain db size is client specific, it doesn't belong in the ethereum 2.0 api. I'll have to take a look at how the metrics are exposed via grafana when I get a chance.

**Comment by terencechain** [comment]
Chain size is largely determined by the type of the node the operator runs. One can choose to run a validator only node (2.5GB) or an archival node (30GB) today. The differences is how often the node saves the state

**Comment by ncitron** [comment]
> Chain size is largely determined by the type of the node the operator runs. One can choose to run a validator only node (2.5GB) or an archival node (30GB) today. The differences is how often the node saves the state

Thats true, which is why I was thinking of doing something like [https://etherscan.io/chartsync/chaindefault](url). It'd be a pain to implement since it would require messing around with all the clients, but would certainly be a very useful graph for people to have access to.

**Comment by Buttaa** [comment]
_added to internal PM tool_

**Comment by Buttaa** [comment]
_added to internal PM tool_
