### ISSUE TITLE
Is it possible to run blockcha.in locally on a mac?

### ISSUE THREAD

**Issue by samlaf** [gobitfly/eth2-beaconchain-explorer#1764]
**Describe the bug**
Following https://github.com/gobitfly/eth2-beaconchain-explorer#developing-locally-with-docker
docker compose up results in
```
 ⠋ prysm The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  0.0s
```

There was also a similar error for the geth container. I managed to point that one to the arm version of the docker image, but prysm containers don't currently support arm (see this [issue](https://github.com/prysmaticlabs/prysm/issues/10119))

**Comment by recy21** [comment]
Hey, this does sound more like a Prysm/Geth vs Mac issue to me.
In addition our project is called beaconcha,in, not blockcha.in.
Not sure you are in the right repo...

**Comment by samlaf** [comment]
That was a typo.
It is a Mac issue though. Images don’t run on arm, which Mac runs. I don’t need this anymore though, so feel free to close.

**Comment by recy21** [comment]
All right, have a nice day
