### ISSUE TITLE
Invalid `chain id missmatch` error message

### ISSUE THREAD

**Issue by mxmar** [gobitfly/eth2-beaconchain-explorer#1839]
**Describe the bug**
There is an issue in `explorer` codebase. Please take a look on https://github.com/gobitfly/eth2-beaconchain-explorer/blob/e4c3be4dee2ef6a39644134a381f210efdc27527/cmd/explorer/main.go#L151 line. 

It generates log like:
```
time="2023-02-20T14:21:47Z" level=fatal msg="chain id missmatch: erigon chain id 2022, geth chain id 2022, requested chain id 2022"
```

**To Reproduce**
1. Run `erigon`, `geth` and `lighthouse`. To reproduce error, `geth` should have different `chainID` than `lighthouse` and `erigon` (`execution` incompatible with `consensus` config). Let's say: `gethChainID=1234`, `conensusExpectedExecutionChainID=2022`
2. Run explorer service (for example from `docker-compose` or from binary)
3. Check `explorer` (`exporter` service in `docker-compose`) logs for `level=fatal msg="chain id missmatch`
4. See invalid error message: `erigon chain id 2022, geth chain id 2022, requested chain id 2022`

**Expected behavior**
You should be able to see a valid error message: 
```
time="2023-02-20T14:21:47Z" level=fatal msg="chain id missmatch: erigon chain id 2022, geth chain id 1234, requested chain id 2022"
```

**Screenshots**
No screenshots, just text log message:
```
time="2023-02-20T14:21:47Z" level=fatal msg="chain id missmatch: erigon chain id 2022, geth chain id 2022, requested chain id 2022"
```

**Desktop (please complete the following information):**
All possible.

**Phone (please complete the following information):**
All possible.

**Additional context**
How to fix that?

Change 
https://github.com/gobitfly/eth2-beaconchain-explorer/blob/e4c3be4dee2ef6a39644134a381f210efdc27527/cmd/explorer/main.go#L151 line to:
```go
logrus.Fatalf("chain id missmatch: erigon chain id %v, geth chain id %v, requested chain id %v", erigonChainId.String(), gethChainId.String(), fmt.Sprintf("%d", utils.Config.Chain.Config.DepositChainID))
```

**Comment by recy21** [comment]
Thank you for your interest in our project.
Fixed in [#2157](https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2157)
