### ISSUE TITLE
Specify the slots per epoch

### ISSUE THREAD

**Issue by avenbreaks** [gobitfly/eth2-beaconchain-explorer#1859]
**Describe the error**
How to getting **SLOTS_PER_EPOCH** on own blockchain running **SECONDS_PER_ETH1_BLOCK** 2sec ? im getting error after start the explorer config 

Execution   : `GETH`
Consensus : `Lodestar` 

```
./bin/explorer --config config/default.config.yml 
INFO[0000] compile time check completed                  module=templates
INFO[0000] did init config                               configName=cartenz depositChainID=18251838 depositContractAddress=0x0420420420420420420420420420420420420420 depositNetworkID=18251838 genesisTimestamp=1677415012
INFO[0000] starting                                      chainName=cartenz config=config/default.config.yml version=v1.12.0-58-g23e39c4d
FATA[0000] invalid chain configuration specified, you must specify the slots per epoch, seconds per slot and genesis timestamp in the config file 
```

config.yaml CL : https://txt.mariomichel.com/?4f12e93511775809#8aqfi63MoogzsAz7qzmTPebghSJCxJwUSGqonwz1dwc8
config.yaml Beacon : https://txt.mariomichel.com/?9fe12b3099e5f64f#FPPzwNUmykLwfcutxMZ4zmpUHm4HmnQHGggGjsVepXpC

**Screenshots**
![image](https://user-images.githubusercontent.com/93043826/221496776-0f267c67-ebb0-41d9-805f-fd0768d735d7.png)
![image](https://user-images.githubusercontent.com/93043826/221497305-df2f8cac-1624-491d-a77d-95f99d6e257f.png)

**Desktop (please complete the following information):**
 - Browser [ chrome ]

**Additional context**

**Comment by avenbreaks** [comment]
@protolambda can you check my config sir ?

**Comment by recy21** [comment]
@avenbreaks you didn't defined a **chain.name**, so no default config (located in config/*) can be applied.

So you have to provide all info normally provided in these files, see config/mainnet.chain.yml for example.

**Comment by Ameralameri** [comment]
0x20fE9F5896A3021Ca6eA78005a15AE954dC134E6
