### ISSUE TITLE
Feature request: cloud storage of Slashing Protection files?

### ISSUE THREAD

**Issue by uwuforever** [gobitfly/eth2-beaconchain-explorer#1884]
So since many validators have system monitoring set up to a Beaconchain endpoint, which regularly reports system statistics, could that same endpoint be extended to also report previously signed validator messages uploaded alongside its system statistics? It'd be effectively an always up-to-date slashing protection DB, as opposed to having to manually export and back up files that quickly go out of date. 

On startup, and maybe every few hours, the validator client could send a blank request to download the latest file for that account.

**Comment by recy21** [comment]
Thank you for your interest in our project.
But we don't want users to rely on our feature and compromise the network during downtime. Therefore, I will close this function as unplanned.
