### ISSUE TITLE
Display APR/APY

### ISSUE THREAD

**Issue by MysticRyuujin** [gobitfly/eth2-beaconchain-explorer#190]
# Feature Request
It would be cool if there was a APR/APY projection feature on the dashboard for validators.

**Comment by Buttaa** [comment]
@MysticRyuujin almost impossible to do because eth2 has so many variables that change with every epoch... 
see here https://beaconcha.in/calculator 
change one of the network factors and see how the return changes.

**Comment by MysticRyuujin** [comment]
You know how long the validator has been online, and how much eth has been earned past X, a real time current earnings in percent extrapolated to the year, while highly fluctuating, seems like it's possible.

**Comment by Buttaa** [comment]
@MysticRyuujin  "impossible" was the wrong word, but pretty much meaningless and missleading for the user.
> long the validator has been online, and how much eth has been earned past X

the network factors are independent from your own validator, and its past doesn't mean much for the future.

**Comment by MysticRyuujin** [comment]
Tell that to literally everything DeFi representing APR/APY that changes every block.

If you don't want to implement it, ok, I'm not interested in arguing.

**Comment by Buttaa** [comment]
@MysticRyuujin APR has been added! :) 

https://beaconcha.in/validator/0xb0733738acaa0cf9fe8d26739e1cafd98b04b5d63bbb50926479768280a45492a29681be2624c5e79b87a8c7e0c75184

**Comment by chfast** [comment]
Can you increase the precision of APR to at least one decimal place?
