### ISSUE TITLE
Stale validator deposit analysis

### ISSUE THREAD

**Issue by timjp87** [gobitfly/eth2-beaconchain-explorer#192]
Hi,

I'm curious just how many missed slots are due to people who in the past week have never started their validator after making a deposit and it being included into the active set.

My plan is to only look at "active_offline" validators as a validator who has attested in the past two epochs can not be stale.
That's 5819 validators. For them I would need all attestations and their status so I can check if any attestation in that array matches the condition outcome === "Attested".  As soon as this condition is met the validator is not stale otherwise it will be stale. The motivation behind this is to calculate an adjusted participation rate as stale deposits are probably not a problem on Mainnet when there is actually something at stake.

I tried to data mine it from the website with a python script and thread pool to do the work in parallel but it would be over 70.000 requests.

I think it would be interesting to have this on the website. If not I would like to do this with the help of a PostgresSQL dump that I can import locally.

**Comment by timjp87** [comment]
As an additional metric this would be interesting when put into context with the the age of the activation. 
It could be plotted with time since genesis on X axis and percentage of stale deposits on the Y axis. Maybe 30% of the active_offline validators are stale and out of those 70% are stale since genesis and only 5% since last two days.

**Comment by peterbitfly** [comment]
Hi,

we have just added a basic api for beaconcha.in. Please have a look at the docs available at https://beaconcha.in/api/v1/docs/ if it allows you to query the information you are interested in. As an alternative, as the explorer is open source, you could set up your own instance and then query your own database directly for the information you need. Unfortunately we are unable to export or provide direct access to our production database.
