### ISSUE TITLE
Discrepancy between beaconcha.in and beaconscan.com

### ISSUE THREAD

**Issue by torfbolt** [gobitfly/eth2-beaconchain-explorer#197]
From user Bad_Investment@ethstaker discord:

Who should I report a discrepancy on beaconcha.in to?
https://beaconcha.in/block/39846
https://beaconscan.com/slot/39846
Different proposers indicated for this block

Block and state root are identical, just different proposers

**Comment by peterbitfly** [comment]
Fixed with https://github.com/gobitfly/eth2-beaconchain-explorer/commit/1871dcae5f4ec6721b809536f6a2cce2f06a2676
