### ISSUE TITLE
participation rate chart data missing

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#1984]
The [participate rate chart](https://beaconcha.in/charts/participation_rate) seems to only have ~1 week of data.

<img width="1102" alt="Screenshot 2023-03-23 at 12 34 11" src="https://user-images.githubusercontent.com/731743/227205033-2dea313b-e967-4ddf-8d2d-aee7b6ce2171.png">

**Comment by Buttaa** [comment]
> The [participate rate chart](https://beaconcha.in/charts/participation_rate) seems to only have ~1 week of data.
> 
> <img alt="Screenshot 2023-03-23 at 12 34 11" width="1102" src="https://user-images.githubusercontent.com/731743/227205033-2dea313b-e967-4ddf-8d2d-aee7b6ce2171.png">

thanks @JustinDrake  - fixed: https://beaconcha.in/charts/participation_rate
