### ISSUE TITLE
[Feature Description] Rotki needs/integration

### ISSUE THREAD

**Issue by LefterisJP** [gobitfly/eth2-beaconchain-explorer#1995]
## Introduction

I am writing this issue after prompt by @Buttaa. The point is to explain what are the needs for rotki and why we use beaconchain in order to see if there is ways to optimize our use of the beaoncha.in api by combinding them and making less queries.

## What rotki need

What rotki needs is a per validator:

- proposals and their transactions/mev reward and all that
- validator income per day in the consensus layer
- withdrawals, either full or partial per validator

(may be forgetting something and will edit the issue)

**Comment by guybrush** [comment]
Regarding "validator income per day in the consensus layer": how do you define a day? Would it be sufficient for your use-case if we only give you the data for beaconchain-days, that is for every 225 epochs?

**Comment by LefterisJP** [comment]
no we would need 24 hours. Just like you already do in the stats page per validator. Where you show how much the validator earned per day.

**Comment by recy21** [comment]
Thank you for your interest in our project.
Created an internal ticket, will update here if we have new information.

**Comment by Buttaa** [comment]
Will be considered in v2 api - closing.
