### ISSUE TITLE
Chart: Difference between holding 32ETH and Staking ETH

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#200]
(32 ETH * ETH Price) vs (32ETH + avg. accumulated ETH * ETH price)

**Comment by guybrush** [comment]
This would be the reward multiplied by ETH-price over time?

**Comment by Buttaa** [comment]
yes @guybrush  
avg. accumulated ETH is basically this [chart ](https://beaconcha.in/charts/validator_income)
