### ISSUE TITLE
[API] The query param `limit` doesn't work as intended `/balancehistory`

### ISSUE THREAD

**Issue by wpoulin** [gobitfly/eth2-beaconchain-explorer#2001]
**Describe the bug**
The query param `limit` 
https://beaconcha.in/api/v1/validator/__INSERT_KEY__/balancehistory?limit=1

**To Reproduce**
1. Go to `https://beaconcha.in/api/v1/docs/index.html#/Validator/get_api_v1_validator__indexOrPubkey__balancehistory`
2. Set an `indexOrPubkey`
3. Set the query param `limit` to `1`
4. It returns 2 items. Setting the limit to N, the number of results is N + 1

**Expected behavior**
It should return a single item (limit=1)

**Comment by peterbitfly** [comment]
Thanks for the reports, we are currently testing a fix that should get deployed to production shorty.
