### ISSUE TITLE
Keep number of entries per page

### ISSUE THREAD

**Issue by f5b7** [gobitfly/eth2-beaconchain-explorer#203]
There are various pages where I can select how many entries should be displayed per page (default 10, choice: 10, 25, 50, 100).

After refreshing a page this is reset to the default, so I always have to set it (e.g. to 100) again.

I would appreciate if this would either be saved in a cookie or as a user account setting (choosing another default value, which only applies if signed in).

**Comment by Buttaa** [comment]
hi @f5b7 , sorry for the late response, but this was fixed a while ago. 

You can test it here https://beaconcha.in/slots
