### ISSUE TITLE
Move "beaconcha.in" from email subject to "from" 

### ISSUE THREAD

**Issue by newearthmartin** [gobitfly/eth2-beaconchain-explorer#2040]
Currently emails are coming from "no-reply" and it says beaconcha.in in the subject:

![Screenshot_20230403_094321_Gmail](https://user-images.githubusercontent.com/1507266/229513610-ac4b482a-0dac-45fe-8393-d358cc719b37.jpg)

It would be better if the sender was `"beaconcha.in <no-reply@beaconcha.in>"`, then email clients would display the email from "beaconcha.in" and the email subject could just be the notification.

**Comment by recy21** [comment]
Will be part of the next release, thanks
