### ISSUE TITLE
The calculation for the Total Rewards line is off

### ISSUE THREAD

**Issue by xanatos** [gobitfly/eth2-beaconchain-explorer#2099]
I think the calculations for the Total Rewards is off. The Internal Transaction https://beaconcha.in/address/0x87610a9884e198a07232d03a1c68c6cfd4527db8#internalTxns isn't calculated in the tooltip.

And even the CL "line" of the tooltip is wrong. 

https://beaconcha.in/dashboard?validators=369529

Compare
![image](https://user-images.githubusercontent.com/821344/232060036-77d3b7b3-0aec-45ef-9697-8875651ec290.png)

vs
![image](https://user-images.githubusercontent.com/821344/232060133-f8ee2fb9-0b83-4f15-acaf-cb4ca0480e55.png)

Clearly if the ETH were automatically withdrawn, they were rewarded at some point.

**Comment by recy21** [comment]
Hey, created an internal ticket, will update here if there is a feedback. Thanks for you report.

**Comment by MauserBitfly** [comment]
@xanatos : I don't think the internalTx is the source of the problem as it was triggered by the block proposal of Validator 369535 and not 369529 and therefor should not be added to the rewards of 369529. 

Here is the related [block](https://beaconcha.in/block/17031632).

We are investigating why the CL Rewards are not 100% correctly displayed.

**Comment by recy21** [comment]
Will be part of next Release

**Comment by recy21** [comment]
Already live on mainnet, closing this issue
