### ISSUE TITLE
Improve Withdrawal time prediction

### ISSUE THREAD

**Issue by nazar-kuzo** [gobitfly/eth2-beaconchain-explorer#2100]
**Describe the bug**
Once withdrawals are enabled, the new tab “Withdrawals” is showing historical withdrawals and next withdrawal time occurring.

But this prediction is not taking into account the activation queue that is affecting the wait time. And what user sees that expected withdrawal is in ~20 hours and it is not changing at all for a day or so.

**Expected behavior**
I would expect that algorithm would take into account the activation/exit queue in order to properly estimate the total wait time. Since current estimated time is valid only when activation/exit queue is empty

**Additional context**
Since all recently activated validators are eligible for withdrawal and will be processed first until next withdrawal iteration begins. That makes validators with index < current withdraw index wait until activation queue is empty and then current estimated time would be correct.

**Comment by odajuice87** [comment]
I SEE

**Comment by odajuice87** [comment]
SO IT SAYS ON THE 19TH  FOR NEXT WITHDRAWL IS THAT WHEN IT WILL STARTS?

**Comment by Buttaa** [comment]
Hi @nazar-kuzo , there are a few known withdrawal-related bugs, 

1. The calculation for the Total Rewards line is off
<https://github.com/gobitfly/eth2-beaconchain-explorer/issues/2099>

2. Total rewards is incorrect
https://i.imgur.com/nEYoZZG.png

3. Expected withdrawal amount changes unexpectedly

4. Next-withdrawal-estimation is wrong
-----

We have an internal ticket for it - closing the issue:

**Comment by phpmac** [comment]
> SO IT SAYS ON THE 19TH FOR NEXT WITHDRAWL IS THAT WHEN IT WILL STARTS?

No one to answer this question?

**Comment by odajuice87** [comment]
I'm a orry yes

**Comment by odajuice87** [comment]
My apologies  yes the 19th when it will start yes
