### ISSUE TITLE
exited validator shows nothing in "Validator History" or "attestations"

### ISSUE THREAD

**Issue by newearthmartin** [gobitfly/eth2-beaconchain-explorer#2101]
**Describe the bug**
I exited my validator and it's scheduled to exit in the future at epoch 195999.

<img width="596" alt="Screenshot 2023-04-15 at 14 03 40" src="https://user-images.githubusercontent.com/1507266/232240304-9d103f6d-68ff-4e13-848c-ae9bc55664c0.png">

It seems that all calculations now are based as if "now" is epoch 195999, so there is no data:

<img width="428" alt="Screenshot 2023-04-15 at 14 04 06" src="https://user-images.githubusercontent.com/1507266/232240375-09b73d5a-29c8-4dbb-8e07-99ccb10c3a28.png">

<img width="846" alt="Screenshot 2023-04-15 at 14 04 45" src="https://user-images.githubusercontent.com/1507266/232240516-3493a1d5-f018-488d-b9db-405638b568a5.png">

**To Reproduce**
1. Go to an exited validator that has an exit epoch in the future
2. Check "validator history" or "attestations" or other

**Expected behavior**
Even if the validator is set to exit in the future, still it should show latest attestations

**Comment by Buttaa** [comment]
> **Describe the bug** I exited my validator and it's scheduled to exit in the future at epoch 195999.
> 
> <img alt="Screenshot 2023-04-15 at 14 03 40" width="596" src="https://user-images.githubusercontent.com/1507266/232240304-9d103f6d-68ff-4e13-848c-ae9bc55664c0.png">
> 
> It seems that all calculations now are based as if "now" is epoch 195999, so there is no data:
> 
> <img alt="Screenshot 2023-04-15 at 14 04 06" width="428" src="https://user-images.githubusercontent.com/1507266/232240375-09b73d5a-29c8-4dbb-8e07-99ccb10c3a28.png">
> 
> <img alt="Screenshot 2023-04-15 at 14 04 45" width="846" src="https://user-images.githubusercontent.com/1507266/232240516-3493a1d5-f018-488d-b9db-405638b568a5.png">
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to an exited validator that has an exit epoch in the future
> 2. Check "validator history" or "attestations" or other
> 
> **Expected behavior** Even if the validator is set to exit in the future, still it should show latest attestations

Hi, thanks for reporting. We are aware of this issue and have an internal ticket for it. 
(closing this issue)

**Comment by Buttaa** [comment]
Hi, thx for reporting. We will take a look soon.

**Comment by Buttaa** [comment]
hi @newearthmartin , this was fixed a few weeks ago. Please re-open if you still find the issue

**Comment by newearthmartin** [comment]
Thanks! My validator has exited already long time ago so I can't verify.
