### ISSUE TITLE
At present, is it necessary to run the erigon client to run eth2-beaconchain-explorer?

### ISSUE THREAD

**Issue by cppfuns** [gobitfly/eth2-beaconchain-explorer#2103]
i have this problem https://github.com/gobitfly/eth2-beaconchain-explorer/issues/1828
I checked the source code https://github.com/gobitfly/eth2-beaconchain-explorer/blob/6a94af7ab391ba4782c71357386da5468210dd7e/cmd/explorer/main.go#L134
```
rpc.CurrentErigonClient, err = rpc.NewErigonClient(utils.Config.Eth1ErigonEndpoint)
if err != nil {
	logrus.Fatalf("error initializing erigon client: %v", err)
}
```
At present, is it necessary to run the erigon client to run eth2-beaconchain-explorer? My eth2 solution is composed of prysm and geth, why must the erigon client be introduced?

Thanks for the open source eth2-beaconchain-explorer project

**Comment by recy21** [comment]
Hey, currently we only support Lighthouse & Erigon.
Explorer will probably run with others as well (e.g. Geth & Prysm), but with that there will be some parts that don't work properly, so officially speaking: **Lighthouse & Erigon is mandatory atm.**

**Comment by cppfuns** [comment]
> Hey, currently we only support Lighthouse & Erigon. Explorer will probably run with others as well (e.g. Geth & Prysm), but with that there will be some parts that don't work properly, so officially speaking: **Lighthouse & Erigon is mandatory atm.**

Let me submit a suggestion, such key information can be explained in an obvious place, thank you for your reply

**Comment by cppfuns** [comment]
> Hey, currently we only support Lighthouse & Erigon. Explorer will probably run with others as well (e.g. Geth & Prysm), but with that there will be some parts that don't work properly, so officially speaking: **Lighthouse & Erigon is mandatory atm.**

Let me submit a suggestion, such key information can be explained in an obvious place, thank you for your reply
