### ISSUE TITLE
Stats endpoint returns null values for certain validators

### ISSUE THREAD

**Issue by pincente** [gobitfly/eth2-beaconchain-explorer#2117]
**Describe the bug**
Recently, the stats endpoint began to return null values for the various balance fields on their first day of history.

**To Reproduce**
https://beaconcha.in/api/v1/validator/stats/378872?end_day=516&start_day=516
https://beaconcha.in/api/v1/validator/stats/20910?end_day=-1&start_day=-1

**Expected behavior**
Proper values for the various balance fields:
https://beaconcha.in/api/v1/validator/stats/209101?end_day=257&start_day=257

**Additional context**
Well done on adding the day params to this endpoint, thanks :+1:

**Comment by recy21** [comment]
Created an internal ticket, will update here if we have new information. Thanks for reporting the issue.

**Comment by Buttaa** [comment]
Hi @pincente , the behaviour looks as intended to me. 

Let’s consider the [378872](https://beaconcha.in/validator/378872#deposits) validator first. You can see that the deposit happened in epoch 116324  which is still day 516.
However balances only get set for the epoch after a deposit, so 116325 which is day 517. This is also the eligible epoch you can see at the top.

This is the result the [API return](https://beaconcha.in/api/v1/validator/stats/378872?end_day=516&start_day=516). For day 516 you only have the deposit and for day 517 the balance with no further deposits.
You will have this view for every validator where the deposit happened in the last epoch of the day.

For genesis validators like [20910](https://beaconcha.in/validator/20910#deposits) this works a bit differently. As you can see if shows the deposit for epoch 0, the same as the eligible epoch, but there exists special handling for deposits in slot 0 where we say for the validator stats that they happened on day -1.

This is the resulting [API return](https://beaconcha.in/api/v1/validator/stats/20910?end_day=0&start_day=-1). Like before for day -1 you only have the deposit and for day 0 the balance with no further deposits.

If you want I could change the return for the 8 balances from nil to 0. Are there other changes required?

The behaviour is the same on prater, see e.g.
[Validator 210384](https://prater.beaconcha.in/validator/210384#deposits) 
https://prater.beaconcha.in/api/v1/validator/stats/210384?end_day=38&start_day=0
Epoch 8550 is the first of a new day.

**Comment by pincente** [comment]
Thanks for the detailed response @Buttaa, makes sense. No need to make any changes at this point. Cheers and keep up the good work.
