### ISSUE TITLE
Activation date UTC tooltip time is quite funky.

### ISSUE THREAD

**Issue by nalepae** [gobitfly/eth2-beaconchain-explorer#2160]
**Describe the bug**
**On the screenshot**: Local time (8 May...) is OK, but tooltip (20**20-...**) seems quite funky.
Seems the tooltip is the start of the beacon chain itself (December 1st 2020).

![image](https://user-images.githubusercontent.com/4943830/235717055-e73fea23-542f-4026-aaf9-717febe61352.png)

**To Reproduce**
1. Go to https://beaconcha.in/validator/614532#charts
2. Hover the activation date

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.3.1
 - Browser: Chrome 
 - Version: 112.0.5615.137 (Official Build) (arm64)

**Comment by recy21** [comment]
fixed and will be part of next release

**Comment by recy21** [comment]
Already part of mainnet, closing this issue
