### ISSUE TITLE
Why is the combination of prysm + geth not supported?

### ISSUE THREAD

**Issue by cppfuns** [gobitfly/eth2-beaconchain-explorer#2194]
From the diversity statistics of node distribution, prysm+geth is the largest in terms of number. Our chain is developed based on prysm, currently due to custom parameters, lighthouse cannot run normally,

https://github.com/gobitfly/eth2-beaconchain-explorer/issues/2103#issuecomment-1517830553
@recy21

**Comment by recy21** [comment]
Hey, the answer is simple: "Time".
A lot has happened in the Ethereum world in the last few months, and we're trying to get everything up and running with all the changes. Since we are only a small team, there is simply not enough time to actively support more than one EL/CL node.
