### ISSUE TITLE
Request: publish eth2-client-metrics-exporter in a Docker image

### ISSUE THREAD

**Issue by alexmbird** [gobitfly/eth2-beaconchain-explorer#2209]
Just gave the app a try - it's lovely and I think you have it priced right, I could setup monitoring myself but for two bucks a month it's easier to pay you for a polished experience.

Now for the tiny feature request.  

Running eth2-client-metrics-exporter-linux-amd64 from the command line is a pain and curl-pipe-bash scares me.  Can you publish it in an image on Docker Hub or equivalent so I can run it the same way as the rest of my stack?

**Comment by recy21** [comment]
Thank you for your interest in our project.

I have created an internal ticket and will keep you updated, but not in this issue, as your requests are related to another project (which is certainly used by this project, but should be tracked there). 
So if you want updates to the internal ticket, please create an issue in https://github.com/gobitfly/eth2-client-metrics-exporter and mention me there. I will forward the updates from the internal ticket to the issue there.
