### ISSUE TITLE
README Getting Started is Outdated

### ISSUE THREAD

**Issue by dospore** [gobitfly/eth2-beaconchain-explorer#2233]
**Describe the bug**
Creating an issue ticket to update the README for external contributors. I am happy to take this issue in the process of contributing to a seperate ticket.

**To Reproduce**
1. Go to the README and follow either https://github.com/gobitfly/eth2-beaconchain-explorer#getting-started or https://github.com/gobitfly/eth2-beaconchain-explorer#developing-locally-with-docker

**Expected behavior**
After following the getting started docs should have a running interface and backend. 

**Additional context**
This will be ever evolving but is one of those mundane tasks that I am happy to do as my contribution.

**Comment by Buttaa** [comment]
Thanks @dospore !!
As mentioned, the README will very likely be outdated sooner or later, but it's a great first issue to get familiar with the code base.

**Comment by recy21** [comment]
@dospore :hugs:
