### ISSUE TITLE
FATA[0000] error initializing erigon client:

### ISSUE THREAD

**Issue by NickRHill** [gobitfly/eth2-beaconchain-explorer#2288]
I'm hoping to get the explorer to connect to prysm/geth for pulsechain. 
I'm not a pulsechain dev, so having to experiment with the correct parameters. (Please don't add the genesisValidatorsRoot to utils.go without verifying). 

I'm not running Erigon, yet on start-up explorer is erroring trying to connect to erigon. 

Expected behaviour: Connects to geth
actual behaviour:
Fatal error attempting to connect to Erigon

```
nick@opi:~/build/eth2-beaconchain-explorer$ ./bin/explorer -config config.yaml 
INFO[0000] compile time check completed                  module=templates
INFO[0000] did init config                               configName=pulsechain depositChainID=369 depositContractAddress=0x3693693693693693693693693693693693693693 depositNetworkID=369 genesisTimestamp=1639659600 genesisValidatorsRoot=0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2
INFO[0000] starting                                      chainName=pulsechain config=config.yaml version=v1.26.0-9-g7c5e032b
INFO[0000] initializing erigon client at                 module=rpc
FATA[0000] error initializing erigon client: error dialing rpc node: dial unix: missing address 
nick@opi:~/build/eth2-beaconchain-explorer$ 
```

**Comment by Buttaa** [comment]
> I'm hoping to get the explorer to connect to prysm/geth for pulsechain. I'm not a pulsechain dev, so having to experiment with the correct parameters. (Please don't add the genesisValidatorsRoot to utils.go without verifying).
> 
> I'm not running Erigon, yet on start-up explorer is erroring trying to connect to erigon.
> 
> Expected behaviour: Connects to geth actual behaviour: Fatal error attempting to connect to Erigon
> 
> ```
> nick@opi:~/build/eth2-beaconchain-explorer$ ./bin/explorer -config config.yaml 
> INFO[0000] compile time check completed                  module=templates
> INFO[0000] did init config                               configName=pulsechain depositChainID=369 depositContractAddress=0x3693693693693693693693693693693693693693 depositNetworkID=369 genesisTimestamp=1639659600 genesisValidatorsRoot=0xcf8e0d4e9587369b2301d0790347320302cc0943d5a1884560367e8208d920f2
> INFO[0000] starting                                      chainName=pulsechain config=config.yaml version=v1.26.0-9-g7c5e032b
> INFO[0000] initializing erigon client at                 module=rpc
> FATA[0000] error initializing erigon client: error dialing rpc node: dial unix: missing address 
> nick@opi:~/build/eth2-beaconchain-explorer$ 
> ```

Hi @NickRHill , 
Thank you for raising this issue. Our explorer is currently optimized for the ethereum blockchain. If pulsechain is interested in an Explorer as a Service (EaaS) we encourage them to get in touch with us on [Discord](https://discord.io/beaconchain).
