### ISSUE TITLE
Externally hosted resources / why is there an adserver referenced in the default layout?

### ISSUE THREAD

**Issue by SjonHortensius** [gobitfly/eth2-beaconchain-explorer#232]
While I'm not a huge fan of externally hosted scripts; it's understandable to fetch certain libraries from reputable sources. I do however not understand why there is an adserver in the default `layout.html`:

https://github.com/gobitfly/eth2-beaconchain-explorer/blob/b89fab9297fa9bb27f4b19af8c41cd8a6b4f5130/templates/layout.html#L533

Is this intentional?

**Comment by Buttaa** [comment]
We are hosting our own open source revive server - 

https://github.com/gobitfly/eth2-beaconchain-explorer/blob/93ab701f01fc52b60a25c68578ae75c9ac4c2926/templates/layout.html#L936
