### ISSUE TITLE
add pools "MarsProtocol"

### ISSUE THREAD

**Issue by Jodragon** [gobitfly/eth2-beaconchain-explorer#2338]
Adding MarsProtocol to the ranking? [pools Page](https://beaconcha.in/pools).
Name Of Service- MarsProtocol
Website- www.marsprotocol.com

Thanks in advance.

**Comment by Buttaa** [comment]
@Jodragon 

hi, please open a PR following the column structure visible on the stakingservice page.

**Comment by Jodragon** [comment]
> @Jodragon
> 
> 嗨，请按照 stakingservice 页面上可见的列结构打开一个 PR。

https://github.com/gobitfly/eth2-beaconchain-explorer/pull/2341
