### ISSUE TITLE
How to get my mev relay registered ?

### ISSUE THREAD

**Issue by cexedev** [gobitfly/eth2-beaconchain-explorer#2340]
I am running a mev relay using in goerli test net using flashbots. Is there any form or any api to register my relay on the goerli.beaconcha.in, so that the "MEV Reward Recipient:" and "MEV Block Reward:" section is visible on the respective block explorer.

The end goal here is to display "MEV Reward Recipient:" and "MEV Block Reward:" section like this screenshot and to show name of my own relay where "Flashbots (Relay)" is being displayed.
![image](https://github.com/gobitfly/eth2-beaconchain-explorer/assets/131411446/2dcf4f2f-d268-441a-9319-cab88ce58e2c)

**Comment by Buttaa** [comment]
hi @cexedev Once you have been listed and have provided the required information for a relay at https://ethstaker.cc/mev-relay-list, we can proceed with adding you. Kindly open an issue once this has been completed.

**Comment by cexedev** [comment]
Hi @Buttaa , Our relay has been now listed on the [ethstaker - mev-relay list](https://ethstaker.cc/mev-relay-list) . Please kindly show us the procedure to add it in [goerli.beach](https://goerli.beaconcha.in/).
