### ISSUE TITLE
%age of proposed blocks

### ISSUE THREAD

**Issue by nalepae** [gobitfly/eth2-beaconchain-explorer#2352]
**Describe the bug**
This Sepolia validator did not propose any block: https://sepolia.beaconcha.in/validator/1769#blocks

However, its block proposal rate is `3%` (when it should be IMO `0%`)
![image](https://github.com/gobitfly/eth2-beaconchain-explorer/assets/4943830/98a31708-2932-44a6-909c-0d819351f56c)

**Comment by recy21** [comment]
Good find! Created an internal ticket, will update here if we have new information.

**Comment by recy21** [comment]
Fixed in [v1.33.0](https://github.com/gobitfly/eth2-beaconchain-explorer/releases/tag/v1.33.0)
