### ISSUE TITLE
Slot filter seems to be broken

### ISSUE THREAD

**Issue by nalepae** [gobitfly/eth2-beaconchain-explorer#2594]
**Describe the bug**
On the `Slot` page, the `Block Number / Graffiti / ...` filter seems to be broken:
<img width="1467" alt="image" src="https://github.com/gobitfly/eth2-beaconchain-explorer/assets/4943830/8f587d26-13e6-4b16-98ce-7d33613dcc91">

Writing any value into it (for example `Kiln` to filter on graffitis including the `Kiln` substring) seems to have no effect, even if the corresponding `GET` query is updated: https://beaconcha.in/slots?q=Kiln
<img width="1490" alt="image" src="https://github.com/gobitfly/eth2-beaconchain-explorer/assets/4943830/fc203af4-18b3-44af-89e1-73ff5a321a21">

**Note 1:**
It used to work before

**Note 2:**
The `Show only empty graffiti` check box seems to be broken as well.

**Comment by Buttaa** [comment]
> **Describe the bug** On the `Slot` page, the `Block Number / Graffiti / ...` filter seems to be broken: <img alt="image" width="1467" src="https://user-images.githubusercontent.com/4943830/273201930-8f587d26-13e6-4b16-98ce-7d33613dcc91.png">
> 
> Writing any value into it (for example `Kiln` to filter on graffitis including the `Kiln` substring) seems to have no effect, even if the corresponding `GET` query is updated: https://beaconcha.in/slots?q=Kiln <img alt="image" width="1490" src="https://user-images.githubusercontent.com/4943830/273202223-fc203af4-18b3-44af-89e1-73ff5a321a21.png">
> 
> **Note 1:** It used to work before
> 
> **Note 2:** The `Show only empty graffiti` check box seems to be broken as well.

@nalepae hi, thanks for reporting :) 
this bug has been fixed but not deployed yet. It will probably take a few weeks since we are working on a bigger release.
