### ISSUE TITLE
Missing Withdrawals information on Dashboard

### ISSUE THREAD

**Issue by chrishobcroft** [gobitfly/eth2-beaconchain-explorer#2600]
**Describe the bug**

Only one Validator's information is shown under the "Withdrawals" tab on the Dashboard. This is the case even when there are >1 Validator configured in the dashboard.

**To Reproduce**

1. Go to beaconcha.in/dashboard
2. Add >1 Validator to the dashboard
3. Click on the "Withdrawals" tab
4. Observe that there is only entry (even though all Validators have Withdrawals)

**Expected behavior**

I expect to see all Withdrawals expected for all Validators configured on the Dashboard

Thank you for all the work you do!

**Comment by Buttaa** [comment]
> **Describe the bug**
> 
> Only one Validator's information is shown under the "Withdrawals" tab on the Dashboard. This is the case even when there are >1 Validator configured in the dashboard.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Go to beaconcha.in/dashboard
> 2. Add >1 Validator to the dashboard
> 3. Click on the "Withdrawals" tab
> 4. Observe that there is only entry (even though all Validators have Withdrawals)
> 
> **Expected behavior**
> 
> I expect to see all Withdrawals expected for all Validators configured on the Dashboard
> 
> Thank you for all the work you do!

@chrishobcroft Hi Chris, this is not a bug, but expected in the current version of our explorer. We will cover this use case in our v2 explorer/dashboard which is planned for 2024.
