### ISSUE TITLE
Searching for specific graffiti does not work anymore

### ISSUE THREAD

**Issue by sandakersmann** [gobitfly/eth2-beaconchain-explorer#2642]
Searching for specific graffiti does not work anymore.

Example:
https://beaconcha.in/slots?q=BridgetowerCapital

**Comment by Buttaa** [comment]
> Searching for specific graffiti does not work anymore.
> 
> Example: https://beaconcha.in/slots?q=BridgetowerCapital

Hi, this will be fixed in our next release :)
