### ISSUE TITLE
Dashboard imports incorrect amount of deposits 

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#271]
Eth1 dashboard https://spadina.beaconcha.in/validators/eth1leaderboard  
(0xaC60CA9EeF6EB2D5426Ff3135Db279F8dD0A5286) shows 103 deposits. 

Importing via Eth1 address shows 98 only.

![image](https://user-images.githubusercontent.com/26490734/94524538-08410a80-0233-11eb-926b-f87a7e6e42ac.png)

**Comment by guybrush** [comment]
I think this has been fixed with https://github.com/gobitfly/eth2-beaconchain-explorer/issues/172
