### ISSUE TITLE
Would like to pay someone who can help to run this project locally

### ISSUE THREAD

**Issue by witthus** [gobitfly/eth2-beaconchain-explorer#2721]
Try many times but fail,want to learn how this explorer works.Contact me if anyone who can help to run this locally

**Comment by guybrush** [comment]
Did you take a look at https://github.com/gobitfly/eth2-beaconchain-explorer/tree/master/local-deployment ?

```bash
# clone the repository
git clone https://github.com/gobitfly/eth2-beaconchain-explorer
# start a local chain and run the explorer locally (then browse http://localhost:8080)
eth2-beaconchain-explorer/local-deployment/run.sh start
```

**Comment by witthus** [comment]
Thanks for your response.
yeah,but it requires a lot dependency i don't know.It is possible for me to contact you ? witthu@163.com

**Comment by MasterOwnerETcorps** [comment]
> Try many times but fail,want to learn how this explorer works.Contact me if anyone who can help to run this locally

Yeah I may be able to `run project locally ` on my device.

**Comment by MasterOwnerETcorps** [comment]
> > Try many times but fail,want to learn how this explorer works.Contact me if anyone who can help to run this locally
> 
> Yeah I may be able to `run project locally ` on my device.

**Comment by meijiesky** [comment]
> Try many times but fail,want to learn how this explorer works.Contact me if anyone who can help to run this locally

Wondering whether you figure out how to run this locally.

I have a local private network running with besu client and I have some trouble running the explorer to connect to my local besu client.

**Comment by MasterOwnerETcorps** [comment]
> Try many times but fail,want to learn how this explorer works.Contact me if anyone who can help to run this locally

Yeah use your shell or try in dis mode or strictly html
