### ISSUE TITLE
Error when broadcasting message to set withdrawal address using WAGYU

### ISSUE THREAD

**Issue by mtr980** [gobitfly/eth2-beaconchain-explorer#2761]
**Describe the bug**
Hi, I am trying to set the withdrawal address and using WAGYU to generate signed messages for Gnosis Validators.

**To Reproduce**
1. Wagyu > Network > tried mainnet / Goerli 
2. Generate your BLS To Execute change > Import secret recovery phrase
3. Entered Index number ( according to deposit_data.json file), old Withdrawal add, new withdrawal address, validator index number > WAGYU validate
4. WAGYU generate a signed JSON file
5. Dropping JSON to https://gnosischa.in/tools/broadcast to broadcast > ERROR: can not verify signature: signature does not verify

**Expected behavior**
Broadcast message

**Desktop (please complete the following information):**
 - MAC OS
 - Browser [chrome]

**Comment by Buttaa** [comment]
@mtr980 hi, please join our [discord](https://discord.com/invite/nVGbBnvvnA) and post the signature file in a private ticket so we can try reproducing. thanks
