### ISSUE TITLE
Does the explorer support besu client?

### ISSUE THREAD

**Issue by meijiesky** [gobitfly/eth2-beaconchain-explorer#2788]
Wondering whether beacon explorer supports besu client. If it supports and I have a local besu client running, how can I config the explorer and make it work. Thanks!

**Comment by Buttaa** [comment]
@meijiesky hi, we haven't tried it with besu, but all other EL clients should work with the local deployment.

**Comment by meijiesky** [comment]
> @meijiesky hi, we haven't tried it with besu, but all other EL clients should work with the local deployment.

By "all other EL clients", what clients are officially supported now?
