### ISSUE TITLE
Local deployment failed

### ISSUE THREAD

**Issue by meijiesky** [gobitfly/eth2-beaconchain-explorer#2789]
**Describe the bug**
The local deployment failed

**To Reproduce**
1. cd eth2-beaconchain-explorer
2. git checkout v1.48.1
3. make all
4. cd local-deployment
5. kurtosis clean -a && kurtosis run --enclave my-testnet . "$(cat network-params.json)"

**Expected behavior**
command succeeds

**Screenshots**
<img width="1786" alt="Screenshot 2023-12-25 at 19 57 11" src="https://github.com/gobitfly/eth2-beaconchain-explorer/assets/17771191/2e46cde1-172e-47c3-870c-a1b5f709e4f7">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.1

**Comment by Buttaa** [comment]
Hi, @meijiesky.I am unable to replicate this on my end. It appears to be a local issue. Please note that we do not offer technical support for local setups due to resource limitations.
