### ISSUE TITLE
Slack and Telegram webhook issue

### ISSUE THREAD

**Issue by pmaiorchyk-everstake** [gobitfly/eth2-beaconchain-explorer#2812]
**Describe the bug**
Webhook does not work with telegram or slack due to incorrect response providing for webhook

**To Reproduce**
1. Go to 'https://beaconcha.in/user/webhooks'
2. Click on 'Add webhook'
3. Paste link to slack webhook or telegram bot
3.1 Slack: https://hooks.slack.com/services/XXXXXXXXXXXX/XXXXXXXXXXXXXX
3.2 Telegram: https://api.telegram.org/botXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/sendMessage?chat_id=XXXXXXXXXXXXXX
4. Errors (Pressing "?" on under Retries column)
4.1 Slack 
{
	"Body": "no_text",
	"Status": "400 Bad Request"
}
4.2 Telegram
{
	"Body": "{\"ok\":false,\"error_code\":400,\"description\":\"Bad Request: message text is empty\"}",
	"Status": "400 Bad Request"
}

**Expected behaviour**
Send notification via notification channel

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 120.0.6099.199

**Comment by Buttaa** [comment]
@pmaiorchyk-everstake ,This feature currently supports Discord only as we do not have support for Telegram and Slack. If you wish to send it to other providers, you would need to handle the response on your end first.
