### ISSUE TITLE
Cannot adjust withdrawal amount.

### ISSUE THREAD

**Issue by Thales-de-Milet** [gobitfly/eth2-beaconchain-explorer#2871]
**Describe the bug**

**To Reproduce**

**Expected behavior**
I Can change the current withdrawal address with this new address: 0x24c46606766386Dc1c0bf2574F64e401DE94f894

**Screenshots**

**Desktop (please complete the following information):**
 - Windown: [ windown 11 ]
 - Browser : chrome
 - Version : 1

**Phone (please complete the following information):**
 - OS: [e.g. iOS 14.5]
 - App Version : 22

**Additional context**
Cannot adjust withdrawal amount !

**Comment by Thales-de-Milet** [comment]
#2862 
   "withdrawal output": "0x24c46606766386Dc1c0bf2574F64e401DE94f894".

**Comment by Thales-de-Milet** [comment]
#1389 assigned to #2871

**Comment by Eliyanbeyan** [comment]
![1714166217991](https://github.com/gobitfly/eth2-beaconchain-explorer/assets/168879686/ade366ff-04a2-43ef-8162-def6cdf4dc89)
Advertisement

**Comment by Eliyanbeyan** [comment]
Online advertisement promotion for Alibaba products
