### ISSUE TITLE
Cannot bookmark validator through dashboard to add alerts

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#361]
![firefox_2020-11-14_00-28-05](https://user-images.githubusercontent.com/26490734/99130305-45f5c900-2610-11eb-85ce-bd4484190dff.png)

**Comment by dankrad** [comment]
Same problem here. The "Save all to watchlist" button does nothing.

**Comment by Buttaa** [comment]
@dankrad this should be fixed now
