### ISSUE TITLE
Proposer instead of "Proposed by"

### ISSUE THREAD

**Issue by ethers** [gobitfly/eth2-beaconchain-explorer#38]
"Proposer" instead of "Proposed by" seems clearer as latter suggests a proposal was already made.

With this change, "Missed" instead of "Skipped" seems clearer because proposers are never skipped, but a proposer can miss their chance of proposing.  (While a proposer can deliberately skip their turn, it is not normal behavior, and more likely the proposer went offline and so missed their chance.)

**Comment by qu0b** [comment]
Makes sense, thanks!
