### ISSUE TITLE
Add percentages to block statistics

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#465]
For example in the screenshot below replace "6894" by "6894 (95.75%)". That way we can easily track the progression on a day-to-day basis :)

![Screenshot 2020-12-03 at 09 41 52](https://user-images.githubusercontent.com/731743/100992225-d5c1cf80-354b-11eb-8ae7-3c15c2f14d16.png)

**Comment by guybrush** [comment]
Ah yes that one is easy

**Comment by guybrush** [comment]
let me know if this works for you

**Comment by guybrush** [comment]
we will work on a better chart templates soon 🙃

**Comment by JustinDrake** [comment]
Yay, this is great :)
