### ISSUE TITLE
Incorrect attestation effectiveness

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#467]
See https://beaconcha.in/validator/17419#overview Attestations are missed yet attestation effectiveness is at 100%.

![Screenshot 2020-12-03 at 09 50 16](https://user-images.githubusercontent.com/731743/100993147-f4749600-354c-11eb-879b-a42f5517276b.png)

**Comment by guybrush** [comment]
Yeah we are currently only using the optimal-inclusion-distance of actually executed and included attestations.

Currently for this metric we do not look at
- missed attestations
- orphaned attestations (attestation got included in orphaned block)

Also we are still discussing the definition of "optimal-inclusion-distance" see: https://discord.com/channels/694822223575384095/768206298734788618/783694840000806924

So I agree currently this is not optimal and we will change it

**Comment by JustinDrake** [comment]
As a start it may be good to add the number of missed attestations (and a percentage relative to the total number of epochs since activation).

**Comment by JustinDrake** [comment]
As a start it may be good to add the number of missed attestations (and a percentage relative to the total number of epochs since activation).

**Comment by guybrush** [comment]
Right we will do that
