### ISSUE TITLE
Add voluntary exits page

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#470]
It would be great to add a page listing all voluntary exits so far, similar to the slashings page (https://beaconcha.in/validators/slashings).

![Screenshot 2020-12-03 at 10 38 52](https://user-images.githubusercontent.com/731743/100998689-bfb80d00-3553-11eb-9ac3-43bedaa86474.png)

**Comment by guybrush** [comment]
this will come with a bigger pr i am working on
