### ISSUE TITLE
Add burn/mint statistics

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#471]
Burn includes:

1) failed deposits (1 deposit affected so far)
2) slashing penalties (1 validator affected so far)
3) penalties from missed attestations (hundreds of validators affected)
4) inactivity leak penalties

Mint is the sum of all rewards.

**Comment by guybrush** [comment]
We have actually a chart for that but it is disabled for performance reasons :D 

Will enable it soon, along with other new charts (need to get more data into the db to make this easier).

**Comment by bsean95531-prog** [comment]
Mint

**Comment by Buttaa** [comment]
_added to internal PM tool_
