### ISSUE TITLE
Extraneous block count for December 4

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#487]
There should be 7200 blocks per day. The UI shows 7200 blocks for December 2 and December 3 but strangely for December 4 it shows 7201 blocks.

![Screenshot 2020-12-05 at 09 30 12](https://user-images.githubusercontent.com/731743/101239052-82cb5200-36dc-11eb-9972-e84135b59279.png)

**Comment by Buttaa** [comment]
@JustinDrake There was a Proposer Violation (double proposal) on this date. [Validator 18177](https://beaconcha.in/validator/18177#blocks)
 7201 proposed blocks is technically correct.
