### ISSUE TITLE
Slashed by "Untitled"

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#488]
For some reason some of the "Slashed by" validators show up as "Untitled" (as opposed to their index).

![Screenshot 2020-12-05 at 09 52 37](https://user-images.githubusercontent.com/731743/101239464-a774f900-36df-11eb-8b82-ccd4f19ae9a0.png)

**Comment by Buttaa** [comment]
@JustinDrake  the user probably has changed its Name, you can do that by signing an eth1 message 

![firefox_2020-12-05_13-43-45](https://user-images.githubusercontent.com/26490734/101243339-eb77f600-36ff-11eb-9fb0-2dfbb5ae16bf.png)

**Comment by Buttaa** [comment]
Closing this @JustinDrake , please re-open if this is still an issue.
