### ISSUE TITLE
Show block rewards

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#492]
It would be fantastic to show the block rewards (and their breakdown) for proposers. (Note that rewards are accounted for at the end of every epoch via [`process_rewards_and_penalties`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#process_rewards_and_penalties) but can still be calculated on a block-by-block basis.)

**Comment by Buttaa** [comment]
@JustinDrake The new validator view should cover this https://beaconcha.in/validator/1
Let me know what you think :)

**Comment by JustinDrake** [comment]
The new validator view looks really neat but I can't see where the block rewards are 😂

**Comment by Buttaa** [comment]
> The new validator view looks really neat but I can't see where the block rewards are 😂
@JustinDrake  right now we only have the balance change per epoch (block reward + attestation), and it is not trivial to just determine the block reward. Does any of the eth2 api's return the block reward?

**Comment by JustinDrake** [comment]
> Does any of the eth2 api's return the block reward?

Not that I'm aware of. If you guys are limited by the API then maybe worth closing this issue :)
