### ISSUE TITLE
Dashboard does not adapt to currency switch (Top side)

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#504]
![firefox_2020-12-07_13-33-43](https://user-images.githubusercontent.com/26490734/101351397-d4b4d900-3890-11eb-81ae-bd7012744a98.png)

**Comment by ph1go** [comment]
It's fixed-ish but in the CSS, the :after tag still puts ' Eth' after the currency unit.

**Comment by Buttaa** [comment]
Currency change does not change it for the ETH price in the header 

![firefox_2020-12-10_13-37-27](https://user-images.githubusercontent.com/26490734/101773279-df6baa00-3aec-11eb-8072-16ae91a660ff.png)

**Comment by mattcee233** [comment]
![image](https://user-images.githubusercontent.com/48771115/103667105-6afe1c80-4f6d-11eb-9899-2f24aea4dd53.png)
The bigger issue here is that the graphs are just using a fixed FIAT-ETH conversion for the chart and are therefore not superimposing the fact that ETH-USD (in image) changes over time...

**Comment by mattcee233** [comment]
Looks like you could grab a historic list of currency prices and multiply the ETH balance on like 661 of /static/js/dashboard.js
