### ISSUE TITLE
Show number of missed blocks and attestations

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#521]
<img width="530" alt="Screenshot 2020-12-10 at 18 43 19" src="https://user-images.githubusercontent.com/731743/101815593-ab59ae80-3b17-11eb-8542-28d653c9850d.png">

My suggestion would be to display it as "Block proposals [not missed]/[total]" and "Attestations [not missed]/[total]" in the tab labels.

**Comment by Buttaa** [comment]
> <img alt="Screenshot 2020-12-10 at 18 43 19" width="530" src="https://user-images.githubusercontent.com/731743/101815593-ab59ae80-3b17-11eb-8542-28d653c9850d.png">
> 
> My suggestion would be to display it as "Block proposals [not missed]/[total]" and "Attestations [not missed]/[total]" in the tab labels.

![image](https://user-images.githubusercontent.com/26490734/147100458-137e86b4-083a-4628-80e2-3c644eec0269.png)

hi justin, are you happy with the current solution?

**Comment by JustinDrake** [comment]
yep, that's great!
