### ISSUE TITLE
The ad is blinking

### ISSUE THREAD

**Issue by lfjmgs** [gobitfly/eth2-beaconchain-explorer#547]
The page is stretching back and forth. It’s annoying. Could you please make the ad bar fixed?

**Comment by Buttaa** [comment]
> 
> 
> The page is stretching back and forth. It’s annoying. Could you please make the ad bar fixed?

@lfjmgs could you give us more details? screenshot perhaps?

**Comment by qu0b** [comment]
this will fix 9e3dab3
