### ISSUE TITLE
Attribute deposits to msg.sender instead of tx.origin

### ISSUE THREAD

**Issue by banteg** [gobitfly/eth2-beaconchain-explorer#557]
Consider [this transaction](https://etherscan.io/tx/0xae347c7282e828a7590ff0115680f93b5e8c2a254a2127357163c981ede7926f) which makes multiple deposits via a smart contract

The exporter [erroneously attributes](https://beaconcha.in/validators/eth1deposits?q=0x55bc991b2edf3ddb4c520b222be4f378418ff0fa) the deposits to the EOA which has invoked the transaction (`tx.origin`, 0x55Bc) instead of the contract which has done the actual deposits (`msg.sender`, 0xae7).

Since the events don't include the address which has made a deposit, the fix for this would probably involve looking into transaction subcalls (traces). This would bump the eth1 node requirements to an archive node like Turbo Geth.

https://github.com/gobitfly/eth2-beaconchain-explorer/blob/2dcaf74e3007c73c4e78ce07a460f90cdb531144/exporter/eth1.go#L216

**Comment by Buttaa** [comment]
Hi banteg, looks like this was fixed (https://beaconcha.in/tx/0xae347c7282e828a7590ff0115680f93b5e8c2a254a2127357163c981ede7926f) feel free to re-open if not!
