### ISSUE TITLE
Possibility to deactivate snow feature

### ISSUE THREAD

**Issue by Magicking** [gobitfly/eth2-beaconchain-explorer#578]
It's disturbing to try to look for information when there is a lot of animated stuff dangling around.

Could you add a switch to deactivate that?

**Comment by manuelsc** [comment]
It's christmas and it's only for a couple days. I think that's bearable.

**Comment by Magicking** [comment]
Actually, maybe that could be enhanced to celebrate other events such as EthCC, Devcon, with POAP instead of snow :).

Sorry for the bitterness, it brings back Internet Explorer 6 memories.
