### ISSUE TITLE
Add a notification for when the attestation effectiveness goes below 95%

### ISSUE THREAD

**Issue by grok13** [gobitfly/eth2-beaconchain-explorer#584]
My clock was drifting and I was having bad inclusion distance as a result. 
Having a notification would have alerted me faster of the issue.

**Comment by Buttaa** [comment]
I worry that having that kind of notifcation would be extremely sensible, meaning you'd get alerted very often and in most cases there's nothing the user can do about it. I'd instead recommend using the missed attestation notification. 
Closing the issue for now.
