### ISSUE TITLE
Features: Add additional info to ETH1 Deposit Page

### ISSUE THREAD

**Issue by mightypenguin** [gobitfly/eth2-beaconchain-explorer#625]
Page: /validators/eth1deposits

1. Add chart of total pending ETH1 deposits over time
2. Chart or single data point of current validator activation wait time (e.g. 17 days)

**Comment by Buttaa** [comment]
Hi, we added https://beaconcha.in/charts/deposits, which is similar to what you requested back in 2021 😓
