### ISSUE TITLE
Staking Calculator default staking amount is incorrect on firefox

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#702]
![image](https://user-images.githubusercontent.com/26490734/111771457-04ba4200-88ac-11eb-8419-cdf6d372997c.png)

**Comment by Buttaa** [comment]
uBlock seems to cause this bug on firefox and brave

**Comment by guybrush** [comment]
fixed in #703

**Comment by alisscco** [comment]
Thanks 🙏
