### ISSUE TITLE
Attestation Effectivness is incorrect

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#704]
> 1 included at 20 would give a 5% attestation effectiveness for that one attestation, but if the other 9 are good you would have a total effectiveness of 9.05/10.  If 10 were included at 2 you would have a total effectiveness of 5/10

> For the first: 1/20 + 9 * 1/1.  For the second: 10 * 1/2

Source: JGM , https://discord.com/channels/694822223575384095/694822223575384099/816069795015032843

**Comment by billpottle** [comment]
to add to this, for a validator that has never turned on, the explorer is showing one attestation being correct and the rest having being missed.

**Comment by Buttaa** [comment]
The explorer now uses the formula introduced by attestant https://www.attestant.io/posts/defining-attestation-effectiveness/
