### ISSUE TITLE
Explorer down/outdated?

### ISSUE THREAD

**Issue by Youllneverknow0** [gobitfly/eth2-beaconchain-explorer#71]
The explorer seems to be down/outdated?

From the URL I can read that it seems to be trying to display testnet**3**.
As far as I know testnet5 is the current testnet.

Is there a testnet5 version?

Thank you

**Comment by Youllneverknow0** [comment]
Btw: This is the url I tried to use to see the testnet status: https://lighthouse-testnet3.beaconcha.in/

**Comment by guybrush** [comment]
Currently https://beaconcha.in shows the topaz-testnet. 

There is still https://lighthouse.beaconcha.in which shows the testnet5 of lighthouse - but I am not sure if that testnet is still up, we are currently focusing on topaz (which lighthouse will join afaik).
