### ISSUE TITLE
Page login and saved validators

### ISSUE THREAD

**Issue by Edward89crypto** [gobitfly/eth2-beaconchain-explorer#72]
Can we have a login with ETH adress and password not email so that it can save the validators?and can we have a future to add only the eth adress and the page gets the pubkey for the validator deposits?Thx

**Comment by Buttaa** [comment]
@Edward89crypto  sorry for the late response, it's definitely on our list :)

**Comment by Buttaa** [comment]
@Edward89crypto the account feature has been [added ](https://beaconcha.in/register), thank you.
