### ISSUE TITLE
Search blocks by graffiti 

### ISSUE THREAD

**Issue by terencechain** [gobitfly/eth2-beaconchain-explorer#73]
Not sure if this is supported today, I couldn't figure out how to do it. Would be nice to search and filter blocks base on block graffiti

**Comment by qu0b** [comment]
In the search bar at the top right it is possible to query by graffiti although it should to be a unique graffiti name because we limit the number of search results.

Do you think it would be useful to add a filter option to the /blocks view?

**Comment by terencechain** [comment]
i think so : )

**Comment by guybrush** [comment]
You can now search for the graffiti in the blocks-view: https://beaconcha.in/blocks

@terencechain let me know if that does not work for you
