### ISSUE TITLE
Feature Request: Add Scheduled Email Status Report

### ISSUE THREAD

**Issue by JHGrove3** [gobitfly/eth2-beaconchain-explorer#732]
The Dashboard is a great way to keep track of validators and see how they are performing right at that moment.

A great feature would be to allow users to set up an automated status report, which would email them a snapshot of the dashboard information at certain pre-scheduled intervals.

The report could come out daily, weekly, or monthly. It could come at a certain time of day, based on the user's time zone.

It would email them some/all of the key information that is currently shown on the dashboard, including:

For all validators combined:

- Last Day Balance Increase (or Decrease)
- Last Week Balance Increase (or Decrease)
- Last Month Balance Increase (or Decrease)
- Total Balance Increase (or Decrease)

For each validator:

- The public key
- Index
- Current Balance
- State
- Number of Proposals
- Number of Missed Proposals
- Number of Attestations
- Number of Missed Attestations*
- Income for the last 7 days

* This metric is not currently shown on dashboard

The specific list of validators included in the report could be based on the user's dashboard, or based on the validators in the user's watchlist. Optionally, a new checkbox/toggle could be added to each validator in the watchlist labeled "Include in scheduled reports".

This would be very helpful for ongoing long-term reporting, as a user could request a report as of midnight on the first day of the month, for example, and thereby keep a running record of monthly performance.  It would eliminate the need to manually pull data at a certain time of day each week or each month.

**Comment by Buttaa** [comment]
Hi @JHGrove3,

We added https://beaconcha.in/rewards a while ago. Which is a basic report of your income within a specific period.
Most of your requested features are still missing, but we can extend the subpage in the future

**Comment by Buttaa** [comment]
https://github.com/gobitfly/eth2-beaconchain-explorer/issues/960
