### ISSUE TITLE
Bug: Can't Change Email Address to one that includes a Plus symbol

### ISSUE THREAD

**Issue by JHGrove3** [gobitfly/eth2-beaconchain-explorer#733]
The Plus symbol "+" is a valid character in an email address. However it is not currently possible to change your email address on Beaconcha.in to one that includes a plus symbol

Beaconcha.in correctly allows users to subscribe to emails using an email address that includes a plus sign.

But if a user attempts to change their email address to one that includes a plus sign, it doesn't work. The change email process breaks down after clicking the link to validate the new email. When the user tries to log in with their updated email, the system says there is no such address. At that point it is also no longer possible to log in with the old email address.

One reason this is important to fix: As a helpful bonus feature, Gmail allows the use of the plus symbol for email filtering. Everything after the plus (inclusive) but before the @ sign is ignored for email delivery purposes (it all goes to the same Gmail account). But Gmail allows the user to sort and filter email based on the extra information after the plus symbol.

**Comment by guybrush** [comment]
Thank you for pointing this out!
