### ISSUE TITLE
Larger validators (whales) cannot use the dashboard

### ISSUE THREAD

**Issue by tothemoon12342** [gobitfly/eth2-beaconchain-explorer#737]
Please set the hardcoded limit from 301 to 501 here:
https://github.com/gobitfly/eth2-beaconchain-explorer/blob/bf19dd632cb3ee2b38f1c4ea7807a8861810bb40/handlers/search.go#L168

and from 200 to 500 here:
https://github.com/gobitfly/eth2-beaconchain-explorer/blob/4800f274ab7f8f17b6f9be7b052a6d9b69c16131/static/js/dashboard.js#L37

Thanks

**Comment by JHGrove3** [comment]
This could be added as a premium feature, too

**Comment by Buttaa** [comment]
Hi, this will be added as a premium feature soon!
