### ISSUE TITLE
Show number of unique votes per block

### ISSUE THREAD

**Issue by michaelsproul** [gobitfly/eth2-beaconchain-explorer#754]
Currently the page for blocks displays all the votes for a block, but doesn't have a quick way of seeing how many of those votes are unique (i.e. from different validators). Due to inefficiencies in attestation aggregation a single validator's attestation will often be included on chain multiple times, e.g. validator 26's vote for block 939968 was included 6 times on chain: https://beaconcha.in/block/939968

Having a quick at-a-glance count of the number of unique votes would be nice. I hope this wouldn't be too hard to implement, due to indexes, etc?

My motivation for this feature is hunting down blocks that received a low number of votes (often indicating that they were published late, or from a node with poor connectivity).

**Comment by guybrush** [comment]
fixed in #756

**Comment by michaelsproul** [comment]
Awesome! That was a really quick turnaround and just what I wanted, thank you 😌
