### ISSUE TITLE
Block missed in list but proposed in the detail page

### ISSUE THREAD

**Issue by Yoldark34** [gobitfly/eth2-beaconchain-explorer#78]
The attestation appeared missed on the list but proposed in the details page

https://beaconcha.in/validator/a09c5e7520ede03b932d3c06e74699f6770235e2011d3beca4ec77223f09977cf6316b460ebe2bcecedc6ff2d1daa527#pills-attestations
https://beaconcha.in/block/39487

![image](https://user-images.githubusercontent.com/3829890/80119921-9cbf8680-858a-11ea-8655-f7f615d8c938.png)
![image](https://user-images.githubusercontent.com/3829890/80119968-a8ab4880-858a-11ea-804a-9511df5c4a5e.png)

Did i miss or proposed the attestation ?

**Comment by Yoldark34** [comment]
Same on etherscan 
https://beacon.etherscan.io/slot/39487
https://beacon.etherscan.io/validator/163#attestations

**Comment by guybrush** [comment]
Hm as far as I understand you do not understand why the attestation is marked as "Missed" for the validator 163?

The block has been proposed successfully (2/3 have voted) but this validator missed the attestation.

**Comment by Yoldark34** [comment]
Yes i do not understand why it missed it.

The point for the issue is : There should be the same rule for proposed/missed attestation, it appear that this is not the case as there is two different result.

**Comment by Yoldark34** [comment]
Ok, the list in the validator page is showing if the validator has voted or not (attested or missed).
The detail page is showing if the block is proposed or not (proposed or missed).

It's king of misleading that the 2 same UI component differ only by the text, its a little bit too subtle. You can close the issue, this is a UI misunderstanding.
