### ISSUE TITLE
Increase precision (again!) of "Voted" percentage

### ISSUE THREAD

**Issue by JustinDrake** [gobitfly/eth2-beaconchain-explorer#782]
(See previous issue [here](https://github.com/gobitfly/eth2-beaconchain-explorer/issues/440).)

It would be nice to have an extra digit of precision in the "Voted" percentage (e.g. 99.65% as opposed to just 99.6%). Indeed, we expect "Voted" participation to eventually mostly hover around 99.6% and the extra digit will provide significant added information.

<img width="753" alt="Screenshot 2021-05-07 at 11 03 15" src="https://user-images.githubusercontent.com/731743/117433871-e5db4200-af23-11eb-99e6-9844efe9221d.png">

**Comment by Buttaa** [comment]
@JustinDrake  fixed (again!) 😄 
![firefox_2021-06-29_07-46-47](https://user-images.githubusercontent.com/26490734/123743859-2b761480-d8ae-11eb-9540-dabdc69f45ed.png)
