### ISSUE TITLE
/validator/{public_key} always goes to validator 0

### ISSUE THREAD

**Issue by prestonvanloon** [gobitfly/eth2-beaconchain-explorer#8]
Example: https://beaconcha.in/validator/b1971d7f691c3d592b3072e7394ad5a63c1756b9800138d4ae780526be91802edf7ee8db3e6edb5960280e6dc56f3872

Should go to validator 681, but goes to validator 0

**Comment by ppratscher** [comment]
Fixed with https://github.com/gobitfly/eth2-beaconchain-explorer/commit/f0cb65e70c851dd8482b32dfd50b65734c131e42

Thanks for reporting this issue!
