### ISSUE TITLE
Empty validators watchlist

### ISSUE THREAD

**Issue by NicolasMassart** [gobitfly/eth2-beaconchain-explorer#802]
Hi,
When loading the watchlist page, Chrome gives me the following error:
![`DataTables warning: table id=notifications - Ajax error. For more information about this error, please see http://datatables.net/tn/7`](https://user-images.githubusercontent.com/4677568/117214562-52a7ec80-adfd-11eb-8af2-8f544a2eb5c9.png)
and the watchlist is empty even if I added validators to it.

- macOS 11.3 (20E232)
- Chrome Version 90.0.4430.93 (Official Build) (x86_64)

**Comment by Buttaa** [comment]
@NicolasMassart We have had issues on the testnets ~10hours ago. I tried to reproduce this but could not.

Could you provide more information please?
- Testnet (which)? Mainnet?
- How to reproduce?

**Comment by NicolasMassart** [comment]
Yes sorry, here are the details:
This happens on https://beaconcha.in/user/notifications for me, so mainnet.
Just opening this page is enough to get the error.
Then the  whatchlist is empty even if I'm watching some.
The notifications list on the same page is fine:
![image](https://user-images.githubusercontent.com/4677568/117290484-27111a80-ae6e-11eb-873b-c6ba57af85fe.png)

**Comment by NicolasMassart** [comment]
It seems to be fixed now!
Thanks.
