### ISSUE TITLE
Pop-Up Error With Newly Deposited Validator in Watchlist

### ISSUE THREAD

**Issue by dylancaponi** [gobitfly/eth2-beaconchain-explorer#838]
With a validator in the watchlist that is deposited but not yet pending and another validator that is active.

Going to the watchlist causes a pop-up with this message:

`DataTables warning: table id=notifications - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

After removing the deposit/pending validator from watchlist and reloading, no error appears.

**Comment by guybrush** [comment]
Thank you for reporting this!

Should be fixed now.
