### ISSUE TITLE
Imprint web link broken (http status 500)

### ISSUE THREAD

**Issue by redtux** [gobitfly/eth2-beaconchain-explorer#939]
Hi everybody, https://prater.beaconcha.in/imprint reports an http status 500 (Internal Server Error). This is no new issue, but I found no other related issue here - and just waiting for it to be fixed as I did does not seem to work. 🤓

**Comment by redtux** [comment]
Oh no, now the whole site went down. 🤔

**Comment by redtux** [comment]
Hi @Buttaa , it still says "Internal server error" when trying to access https://prater.beaconcha.in/imprint :/ Happy new year and keep up the good work!

**Comment by Buttaa** [comment]
> Hi @Buttaa , it still says "Internal server error" when trying to access https://prater.beaconcha.in/imprint :/ Happy new year and keep up the good work!

Thanks for letting me know, i checked it on the mainnet
