### ISSUE TITLE
Indirectly orphaned blocks are shown as "proposed"

### ISSUE THREAD

**Issue by michaelsproul** [gobitfly/eth2-beaconchain-explorer#942]
On mainnet I found a block at slot [1615425](https://beaconcha.in/block/1615425) which is displayed as "proposed" but is actually orphaned. It's part of a 2-block minority chain 161523 <- 1615425 <- 1615426 which was orphaned in favour of the canonical chain. The head of the minority chain at slot [1615426](https://beaconcha.in/block/1615426) is correctly marked as orphaned, but its parent (the middle block) is not. Note that the block from the canonical chain at slot [1615427](https://beaconcha.in/block/1615427) skips over both.

Block roots for future reference:

- 1615425: 0xddd77e411f7d242b494ea66b2b70aef92f60838279a748209a9572300d2756d8
- 1615426: 0x47bebc502790849e6b04f440db0e79dc5a8313e3ac6f4e93d23229297705bfea

**Comment by Buttaa** [comment]
@michaelsproul we are aware of the issue, there is an open issue regarding this problem https://github.com/prysmaticlabs/prysm/issues/8955

**Comment by michaelsproul** [comment]
Thanks for the info and sorry for the dupe bug report!

I noticed the same thing on lighthouse.beaconcha.in – is that site using Lighthouse as the backend?

**Comment by Buttaa** [comment]
> Thanks for the info and sorry for the dupe bug report!
> 
> I noticed the same thing on lighthouse.beaconcha.in – is that site using Lighthouse as the backend?

It uses prysm and points to the main page, this is a very old page :(

**Comment by michaelsproul** [comment]
Haha ok I suspected that was the case 😅 If you ever want help reviving it, please let us know what features you need from LH!
