### ISSUE TITLE
Machine - not showing Android app - 

### ISSUE THREAD

**Issue by StkrBkrCndleStkMkr** [gobitfly/eth2-beaconchain-explorer#952]
Machine stopped showing up with metrics in Android app. last update  UTC Jul 15, 2021, 8:48 AM
Machine confirmed still working with prop and att

App has other machine still showing and working

Both machines had dropped metrics android app 15/17 July with data loss but still att and pop flawlessly.

1 returned to normal

1 missing in action

Android 11
samsung s10

**Comment by StkrBkrCndleStkMkr** [comment]
also checked api and noted 30 plus confirmations of Android paired devices.. I have 3 I utilise. System must renew service everytime it logs me out and in..

**Comment by manuelsc** [comment]
Can you give a little more insight in your setup and paste your lighthouse/prysm logs please.
Do you have an active premium subscription?

**Comment by StkrBkrCndleStkMkr** [comment]
- yes active sub
- Cannot give you a dump yet, re remote
- 2 machines now not reporting live, can do 7 day history in APP>MACHINES>Last 7d which shows both machines with red dots and last time. BUT both machines are acting normal with ATT and PROP

**Comment by StkrBkrCndleStkMkr** [comment]
system 2
![Screenshot 2021-07-19 11 17 32 AM](https://user-images.githubusercontent.com/87363456/126089227-9b696c43-86d9-4368-b963-857fd8cb6017.png)
![Screenshot 2021-07-19 11 17 24 AM](https://user-images.githubusercontent.com/87363456/126089230-f3bf25c6-3690-4363-9769-cd0bf38997a5.png)
![Screenshot 2021-07-19 11 17 14 AM](https://user-images.githubusercontent.com/87363456/126089231-f8123452-2459-4282-988e-93ed8c549a87.png)
![Screenshot 2021-07-19 11 16 58 AM](https://user-images.githubusercontent.com/87363456/126089234-f43a0065-a90a-4c72-98d1-00f3e774960d.png)

**Comment by manuelsc** [comment]
Thanks for the details! We believe to have identified an issue with our rate limiting service, it should all work now. Let us know if this fixed it for you.  
PS. DM me or Butta and we can give you a free month of goldfish for your troubles. Just let us know whether you are using android or ios :)

**Comment by StkrBkrCndleStkMkr** [comment]
Hi

Has the fix been implemented?

reinstalled, logged in/out

I see no change..

Thanks

**Comment by manuelsc** [comment]
Make sure you use our new metrics endpoint.  
Head over to your beaconcha.in profile -> Mobile and copy the new endpoint url to your machines.

**Comment by manuelsc** [comment]
@StkrBkrCndleStkMkr has this fixed your issue?
