### ISSUE TITLE
Explorer does not know how to handle the genesis 

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#96]
Goes hand in hand with this: https://github.com/gobitfly/eth2-beaconchain-explorer/issues/95

Same for topaz testnet: https://beaconcha.in/block/0 

https://schlesi.beaconcha.in/block/c9cbcb8ceb9b5f71216f5137282bf6a1e3b50f64e42d6c7fb347abe07eb0db82
![Discord_2020-05-11_10-17-48](https://user-images.githubusercontent.com/26490734/81539939-3c458d00-9371-11ea-940f-125b8416d771.png)

**Comment by guybrush** [comment]
I think this is fixed by 9bfb0c3bfa1, please reopen if that is not the case.
