### ISSUE TITLE
Subscriptions are Sent on the Wrong Day of the Month

### ISSUE THREAD

**Issue by JHGrove3** [gobitfly/eth2-beaconchain-explorer#960]
I signed up for a subscription on the User Rewards page:
https://beaconcha.in/user/rewards

My Email is arriving before the end of the month.

I would expect the email to arrive on the 1st of the following month, or at least at Midnight UTC after the last day of the month.

Instead, my July email arrived at 12:01 a.m. UTC on July 31. There was still one more day left in the month.

Moreover, the attached report went from July 1 - July 29.  So it was missing two days, July 30 and July 31.

**Comment by Vahegian** [comment]
https://github.com/gobitfly/eth2-beaconchain-explorer/pull/945

@JHGrove3  we are aware of this issue, we will now send the report on the 1st day of the following month.

**Comment by recy21** [comment]
Fixed in [v1.28.0](https://github.com/gobitfly/eth2-beaconchain-explorer/releases/tag/v1.28.0)
