### ISSUE TITLE
Add weak subjectivity checkpoint API Endpoint

### ISSUE THREAD

**Issue by Buttaa** [gobitfly/eth2-beaconchain-explorer#966]
https://github.com/prysmaticlabs/prysm/blob/develop/proto/prysm/v1alpha1/beacon_chain.proto#L156
for grpc
"/eth/v1alpha1/beacon/weak_subjectivity_checkpoint"

**Comment by Lglivengood** [comment]
How can I be sure this is you I've got to be sure man￼

**Comment by Lglivengood** [comment]
I do not want to let you in someone else's stuff if you don't own it I did not mean to take this and I don't want it I only want literally my little shared that it says it's more like six grand I don't want all this extra￼

**Comment by Lglivengood** [comment]
I mean it's the stupid cats at website thing fault anyway the one that has the cat it's their fault they are the ones that gave me all the directions and introduced me to the people￼

**Comment by Lglivengood** [comment]
I believe you I think it's you I got you￼

**Comment by Lglivengood** [comment]
> https://github.com/prysmaticlabs/prysm/blob/develop/proto/prysm/v1alpha1/beacon_chain.proto#L156
> 
> for grpc
> 
> "/eth/v1alpha1/beacon/weak_subjectivity_checkpoint"

I don't know what to do man like you got to walk me through it literally step-by-step man it is dummy terms as possible I didn't finish high school that's what I'm saying I don't know what I'm doing that I was just trying to make a little extra money

**Comment by Lglivengood** [comment]
> https://github.com/prysmaticlabs/prysm/blob/develop/proto/prysm/v1alpha1/beacon_chain.proto#L156
> 
> for grpc
> 
> "/eth/v1alpha1/beacon/weak_subjectivity_checkpoint"

What if I just hit share on your name will that work￼

**Comment by Lglivengood** [comment]
It won't let me type anything￼
