### ISSUE TITLE
Non-finalized block before finalized

### ISSUE THREAD

**Issue by akolotov** [gobitfly/eth2-beaconchain-explorer#980]
Does it make sense to display prior blocks as non-finalized if the justification and finalization was not happened several epochs but eventually occur again

![image](https://user-images.githubusercontent.com/20793260/128690422-6544dcf7-3ad5-4cba-96e0-9fc127a00935.png)

**Comment by lazike66** [comment]
best

**Comment by guybrush** [comment]
Thanks! 

At some point maybe we should introduce how long it took for every epoch to finalize.

But this is fixed in 3cbf625 for now.
